### ISSUE TITLE
Wrong nomenclature for paramenters under Retransmission

### ISSUE THREAD

**Issue by vikrant8051** [NordicSemiconductor/Android-nRF-Mesh-Library#115]
@roshanrajaratnam @mostafaberg 

Publish(under every Model) -> SET PUBLICATION -> Retransmission 
...... has issue.

Here under Retransmission there are two sub-parameters:

    #RetransmitCount (#RC)
    #IntervalSteps (#IS) 

When user set #RC & #IS values via App, at firmware level those get assign to #IS & #RC respectively.

Means nomenclature is wrong at APP level.

**Comment by roshanrajaratnam** [comment]
@vikrant8051 Thanks for reporting this. Will look and get back

**Comment by roshanrajaratnam** [comment]
Issue confirmed, sorry about this, the parameters were swapped in the message. Will push the changes later!

**Comment by vikrant8051** [comment]
Please inform about it to iOS team because same issue is seen under iOS App.

**Comment by roshanrajaratnam** [comment]
Please create an issue on the relevant repository for this. This makes it easier to keep track of things :) Thanks
