### ISSUE TITLE
byte in Java is signed, so ConfigCompositionDataStatus.pareCompositionDataPages() may not parse those 16bit fields correctly

### ISSUE THREAD

**Issue by foldl** [NordicSemiconductor/Android-nRF-Mesh-Library#119]
For example, if accessPayload[2] = 0xaa, then companyIdentifier  will be 0xffffffaa.

Can I create a pull request for this?

**Comment by roshanrajaratnam** [comment]
Oh yes, please do open a PR and sign the contributor license
