### ISSUE TITLE
Binding key and publishing/subscribing health model

### ISSUE THREAD

**Issue by DuyTrandeLion** [NordicSemiconductor/Android-nRF-Mesh-Library#122]
I used the nRF Mesh app to config the health server to publish to a specific health client, they are all binded with the same app key. I use the app as the provisioner, but the health client doesn't receive any message. 
Edit: after changing the period to 1s it worked, but keeping the default as 100ms it didn't work, I don't know why.

I don't know if the nRF Mesh app or library support binding for health server/client or it's a bug, can it be supported or fixed? Can I fixed it myself? I am not very good at Android developing.

Thank you,
Best regards,
    Duy

**Comment by roshanrajaratnam** [comment]
Hi @DuyTrandeLion sorry for the late reply as I was on vacation. So far the app only supports key binding message on the health server. Did you have trouble binding app keys?

**Comment by DuyTrandeLion** [comment]
Hi @roshanrajaratnam ,
Thank you for your feedback, I don't have problem binding the key, but I don't know where to add the code for period configuration. I wonder when will Nordic support it?

**Comment by roshanrajaratnam** [comment]
@DuyTrandeLion what do you mean by period configuration?

**Comment by DuyTrandeLion** [comment]
@roshanrajaratnam my bad, I mean the publishing period.

**Comment by roshanrajaratnam** [comment]
Closing this issue since there is no updates on this!
