### ISSUE TITLE
ParseOutputOOBActions.selectOutputActionsFromBitMask selects weakest available method

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#123]
**Current behaviour:**
When parsing the mesh node's capabilities the method selectOutputActionsFromBitMask in ParseOutputOOBActions selects the weakest method the node offers.

**Expected behaviour:**
The provisioner selects the strongest available authentication method

**Possible solution:**
Instead of getting the fist element from the list:
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/ad77ce7dd62e3bb3a1db58c629833708990ddb62/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/utils/ParseOutputOOBActions.java#L126

Get the last element from the list:
`            return suppportedActionValues.get(suppportedActionValues.size() - 1);`

---------------------------------------------------------------------------------------

**General question:**
Do you accept contributions? I work with this library on an university project and I there are many more issues that I would like to address.

**Comment by roshanrajaratnam** [comment]
Hi @HaukeRa yes currently the library defaults the weakest. This is something to be addressed down the line.

Yes we do accept pull requests as long as the changes are based on the dev branch. You must also sign the CLA agreement when sending a pull request.

**Comment by HaukeRa** [comment]
Hi @roshanrajaratnam, where can I find the CLA?

I would propose a configuration option for the app to specify it's own capabilities & auth method resolution strategy. I'm willing to create a pull request for this.

**Comment by roshanrajaratnam** [comment]
Hi @HaukeRa Sorry I just saw this. When you send a pull request you are prompted with the CLA to sign it. Also please send the pull request to dev. Thanks for your contribution it really helps with a fresh set of eyes!
