### ISSUE TITLE
Invalid TransactionID being used when sending messages to group addresses

### ISSUE THREAD

**Issue by roshanrajaratnam** [NordicSemiconductor/Android-nRF-Mesh-Library#128]
Incorrect transaction ids are used when sending messages to group addresses. This is due to the fact that the last received sequence number from a node is being used as the transaction Id when sending application layer messages. However when it comes to group addresses a single node's sequence number cannot be used as a transaction id.

**Comment by DomiR** [comment]
What is the plan here? Should we just have a global counter for TIDs? They are valid for only several seconds, so it should not be a problem to use a global counter that overflows... We are using one in our app... The api to set custom TID should stay there though, as we are currently running into problems in high noise environments (>58 wifi nets surrounding us). We need to resend messages with the same TID...

**Comment by roshanrajaratnam** [comment]
Well this is more of an issue related to the app side and using a sequence number of  a particular node as a TID to a group address. However its fixed for now by using the sequence number of the provisioner which increments at all times and also can be used for re-sending as well. I won't remove the custom api. I'll leave it for users to set their own like you had suggested before and it's more convenient that way I guess.
