### ISSUE TITLE
onBlockAcknowledgementSent(byte[] dst) dst is null

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#130]
---

**Describe the bug**
The dst array parameter is always null in callback

**To Reproduce**
1. Set Breakpoint on NrfMeshRepository.java line 716 (first line of onBlockAcknowledgementSent(..))
2. Perform provisioning
3. See that dst is null

**Expected behavior**
dst schould not be null

**Platform details:**
 - Samsung Galaxy S7
 - Android 8.0
 - 1.1.0 Release

**Comment by roshanrajaratnam** [comment]
Fixed internally
