### ISSUE TITLE
Provisioning fails on Nexus 5

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#131]
---

**Describe the bug**
Connecting to a device for provisioning fails on the Nexus 5 smartphone.

**To Reproduce**
1. Open App on a Nexus 5
2. Go to Scanner tab
3. Select node to provision
4. See error: MeshProvisionerActivity opens and closes immediately

**Expected behavior**
Provisioning should happen.

**Platform details:**
 - Device: Google Nexus 5
 - Android 6.0.1
 - 1.1.0 Release

**How to fix**
The Scanner Fragment calls disconnect() before opening the MeshProvisionerActivity which then immediatley on creation calls connect() and observes the connection state. It looks like the disconnect interferes here and closes the activity. Calling connect() on the ViewModel and observing isConnected with a delay of one second makes it run as expected.

**Comment by roshanrajaratnam** [comment]
Thanks for reporting this. I'll give this a go!

**Comment by roshanrajaratnam** [comment]
Fixed Internally.
