### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#133]
**Is your feature request related to a problem? Please describe.**
All new developments on the Andorid support libraries is done under the new androidx. namespace.
All new projects should use libraries with the androidx. namespace. Even though there is the Jettifier tool which translates between android.support and androidx, it only works on artefacts (jar/aar), but not on source.

**Describe the solution you'd like**
Migrate to AndroidX. It's relatively easy with a script: https://gist.github.com/dlew/5db1b780896bbc6f542e7c00a11db6a0#file-script-sh (I had to write the sed commands to a temp file, because it was too long for the commandline on my system)

**Comment by roshanrajaratnam** [comment]
This will also introduce compatibility issues with existing projects. But yes the plan is to move to Android X quite soon.
