### ISSUE TITLE
More broken parcelable implementations

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#134]
---

**Describe the bug**
Some meshprovisioner.transport.MeshMessage subclasses implement Parcelable.
They implement writeToParcel as: `dest.writeValue(mMessage)` whre mMessage is a transport.Message.
But Message does not implement Parcelable so attemptint to parcelize a MeshMessage always fails.

Affected classes:
- GenericOnOffStatus
- GenericLevelStatus
- ConfigCompositionDataStatus
- ConfigModelPublicationStatus
- ConfigNodeResetStatus
- ConfigModelSubscriptionStatus
- VendorModelMessageStatus
- ConfigAppKeyStatus
- ConfigModelAppStatus
- SceneStatus
- ConfigRelayStatus
- LightLightnessStatus
- ConfigNetworkTransmitStatus
- LightCtlStatus
- LightHslStatus
- SceneRegisterStatus
- ConfigProxyStatus 

**To Reproduce**
1. Try to parcelize any of the listed classes

**Logs / Screenshots**
Example Stack trace: 
```
java.lang.RuntimeException: Parcel: unable to marshal value no.nordicsemi.android.meshprovisioner.transport.AccessMessage@5781ffb8
	at android.os.Parcel.writeValue(Parcel.java:1656)
	at no.nordicsemi.android.meshprovisioner.transport.LightHslStatus.writeToParcel(LightHslStatus.java:148)
	at android.os.Parcel.writeParcelable(Parcel.java:1675)
```

**Comment by HaukeRa** [comment]
**MeshModel.java**:
`try{]catch()` block in Constructor from Parcel can result in the same errors as I mentioned in the ProvisionedMeshNode issue. On an exception the parcel remains partially read, so any data after your own is offset now, resulting in wrong data or hard to debug crashes.

**Comment by roshanrajaratnam** [comment]
That was a redundant `try{]catch()`. If i recall correctly this was added to debug a app crash but not being removed after. Fixed internally.

**Comment by HaukeRa** [comment]
Did you account for all the broken MeshMessages in the original bug report?
