### ISSUE TITLE
Database inconsistencies

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#137]
---

**Describe the bug**
Some properties are annotated with Ignored so that they are not persisted in the database. Some of them however are actually set during creation/provisioning etc.

One example is: isProvisioned in BaseProvisionedMeshNode. It is copied from UnprovisionedMeshNode (where it is set to true during the provisioning process).

When persisted and then loaded from database, these fields take their default values, in this case it results in the unexpected behaviour that a `ProvisionedMeshNode` has a propertiy `isProvisioned == false`

**To Reproduce**
1. Provision node
2. see that `isProvisioned` is true for `ProvisionedMeshNode`
3. Restart the App
4. See that `isProvisioned` is false for `ProvisionedMeshNode`

**Expected behavior**
Objects should be fully persisted, unused Fields should be deprecated or better removed.
When a field is not persisted, it should be a computed property (computed from other properties)

**Platform details:**
 - Library Version: 1.1.0 Release

**Comment by roshanrajaratnam** [comment]
Hi @HaukeRa  thanks for reporting this. This has somehow escaped the refactoring that was done for release 1.1.0.

**Comment by roshanrajaratnam** [comment]
Fixed internally
