### ISSUE TITLE
First App Key not persisted

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#139]
---

**Describe the bug**
When Adding App Keys, the branch that is taken when the list of ApplicationKeys is empty does not call `notifyAppKeyAdded(newAppKey)`, resulting in it not beeing persisted in the Room Database. It transiently stays around though, so it only disappears when the app is completely restarted

**To Reproduce**
1. Start with an MeshNetwork without any app keys (or delete all)
2. Add one or more App Keys
3. Restart the App (make sure to remove it from the task list)
4. See first app key is missing

**Expected behavior**
All ApplicationKeys being persisted

**Comment by roshanrajaratnam** [comment]
@HaukeRa Thanks for this. Your testing really helps!

**Comment by roshanrajaratnam** [comment]
Fixed internally.
