### ISSUE TITLE
provide library through gradle implementation 'no.nordicsemi.android:...

### ISSUE THREAD

**Issue by gridar** [NordicSemiconductor/Android-nRF-Mesh-Library#144]
Hi Nordic, thanks for this repo it's great.
Is there a way to easily add the mesh library as dependency ? like `implementation 'no.nordicsemi.android:ble:1.2.0'`
for now the doc say we need to add :
`project(':meshprovisioner').projectDir = file('../../Android-nRF-Mesh-Library/android-nrf-mesh-library/meshprovisioner')` in the settings.gradle. That's working fine but it would be great to have it without cloning the repo on local machines.

**Comment by roshanrajaratnam** [comment]
Hi @gridar, currently we haven't published to jcenter yet. Something we would do sometime in the future. Hope this helps

**Comment by gridar** [comment]
Hello @roshanrajaratnam, any news on putting the lib in jcenter ? That'll help us making a flutter plugin out of it :)

**Comment by roshanrajaratnam** [comment]
@gridar sorry about the delay, been a bit busy with some other priorities. I will take a look at this tomorrow and try to get a version on jcenter.

**Comment by gridar** [comment]
Hello @roshanrajaratnam , just a friendly reminder about jcenter 😃

**Comment by Kleak** [comment]
i think this issue should stay open until you publish the sdk on a package manager.

**Comment by philips77** [comment]
It's there already! Since last week! Sorry, we forgot to update this issue.

**Comment by Kleak** [comment]
awesome thanks

**Comment by philips77** [comment]
Mind that package names have changed, simplified.
