### ISSUE TITLE
JSON files can only be loaded from nrf Mesh directory

### ISSUE THREAD

**Issue by POHakansson** [NordicSemiconductor/Android-nRF-Mesh-Library#145]
---

**Describe the bug**
When trying to load a JSON network config file, it only seems to work if the file's location is the Nordic Semiconductor / nrf Mesh directory.

**To Reproduce**
1. Go to the Settings tab and chose Import from the menu
2. Select a file from for example the "Downloads" folder of your phone
3. The error message says "Invalid file type"

**Expected behavior**
It should be possible to import a network from any directory location.

**Platform details:**
 - Device: Galaxy S7 and Galaxy S8
 - OS: Android 8.0.0
 - 1.1.0 January 16th from Play Store

**Comment by roshanrajaratnam** [comment]
@POHakansson This does not seem to be the case when testing against the same device I have. The json file seems to get imported irrespective of the location. When you say select a file, are you trying to select any json file? It must be a json file or format exported from the same app (different phone).

**Comment by roshanrajaratnam** [comment]
@POHakansson any updates on this?

**Comment by POHakansson** [comment]
I must have made the same mistake several times when I decided to create an issue. Now when I'm testing, it works OK.

Sorry bout that,
Pär-Olof

**Comment by roshanrajaratnam** [comment]
No problem :)

**Comment by i-am-smirnoff** [comment]
Hello!
Let me concretize the issue which exists.

Everything works fine if you navigate to file for import via device internal storage file structure. But if you select a file in "Downloads" as mentioned or if you select a file from "Drive" storage then 'Invalid file type' error occures.

I've managed to import 'invalid' file from "Drive" after changing condition in `if` to `true` here: 
_Android-nRF-Mesh-Library/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/MeshManagerApi.java_

Currently it's line 807:

    if (uri.getPath().endsWith(".json")) {

**Platform details:**

* Device: Lenovo TB-8304F1
* OS: Android 7.0
* Languages: English (United States)
* 1.1.0 January 16th from Play Store
