### ISSUE TITLE
Nodes provisioned by other provisioners

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#150]
**Is your feature request related to a problem? Please describe.**
Currently the app/stack can only communicate with nodes it provisioned itself. But there might be more than one provisioners in a network. So Nodes might exist that are part of the network which the nRf Mesh App doesn't know.

Currently communication with such nodes is not possible at all as the NetworkLayer discards all messages from source addresses which it can't find ProvisionedMeshNodes for in it's database.

**Describe the solution you'd like**
I'm not sure. I want to start a discussion if such a scenario is considered a use-case for this application and if yes, how such a behaviour could be implemented.

**Comment by roshanrajaratnam** [comment]
@HaukeRa yes this is a valid point. When setting up networks it's normal have, multiple provisioners with an address range assigned to each provisioner where they can provision and configure nodes. However once this is completed it will require the configuration json to be imported and merged together and imported in to both provisioners, if they are to control/configure the network. This is not something we have planned to implement so far.
