### ISSUE TITLE
Processing of unsolicited Vendor Specific Messages fails

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#152]
---

**Describe the bug**
When receiving a vendor specific message, the 3-byte long opcode branch in DefaultNoOperationMessageState decides upon the cached `mMeshMessage` what to do with the incomming message.

This only works if we sent a message ourselves previouly that requires a direct answer. So only the first branch for `VendorModelMessageAcked` seems to work. When we send a `VendorModelMessageUnacked` we don't expect an answer so this branch is probably never taken. 

Unsolicited vendor messages are never received because of this (or only if we coincidentally sent a VendorSpecific message right before we received a VendorSpecific message)

**To Reproduce**
1. Configure vendor specific node to send unsolicited messages
2. Make the node send a vendor specific message (e.g. with a button press)
3. Vendor specific message is never handed to `onMeshMessageReceived`

**Expected behavior**
Vendor specific messages should be received, even if we didn't ask for it. Maybe for Vendor Specific messages it is impossible to say if it is acknowledged or not? I think its up to the entity who defined the message to decide upon the opCode if it is an acknowledged message or not.

**Comment by roshanrajaratnam** [comment]
@HaukeRa What's the setup here? is the message sent from the app? if it's an unacknowledged message the app will not receive a message at all.
