### ISSUE TITLE
wrong parsing of 3 byte OpCodes 

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#153]
---

**Describe the bug**
`MeshParserUtils` line 478:
```
 return ((byte) (accessPayload[0] & 0xFF) | (byte) ((accessPayload[1] << 8) & 0xFF) | (byte) ((accessPayload[2] << 16) & 0xFF));
```
& 0xFF after shifting (and then casting to byte) yields always 0. The calculation above always results in the returned opCode always being equal to the first element of the accessPayload only, both bytes after that are effectively discarded.

**Expected behavior**
Applying & 0xFF before shifting results in the desired result as the bytes are converted to an equivalent int without extending the signed bits.
```
 (accessPayload[0]&0xFF ) | (((accessPayload[1]&0xFF) << 8) ) | (((accessPayload[2]&0xFF) << 16));
```

**Comment by HaukeRa** [comment]
Also, the order is twisted. The Mesh specification states in table 3.43, that the byte at position 0 is the most significant byte, the current implementation uses it as the least significant byte

**Comment by roshanrajaratnam** [comment]
Thanks for pointing this out. I have fixed this internally.
