### ISSUE TITLE
BouncyCastleProvider is installed in an error-prone way

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#168]
---

**Describe the bug**
The installing of the Security provider is done within a static block in SecureUtils.java:
`    static {
        Security.insertProviderAt(new org.spongycastle.jce.provider.BouncyCastleProvider(), 1);
    }`
This is very error prone. There is no guaranty when the static block is executed so it can happen that one uses security functionality before the provider is inserted. For the static block to be executed, a code path that actually uses a SecureUtils.java must be executed.

Currently that happens somehow somewhere, but I refactored a little and ran into the error, that during `ProvisioningPublicKeyState#generateKeyPairs()`, the BouncyCastleProvider was not yet installed.

**Expected behavior**
This is a good example why static is "bad". To make things more clear I would move it into a static method that is called early on (for example in a static block in MeshManagerApi, or even better in the constructor)

**Comment by roshanrajaratnam** [comment]
@HaukeRa Thanks for reporting this, I haven't seen this behavior the bouncy castle gets called during the provisioning state or either when sending a generating a mesh message. It does makes sense to not have it set up in a non-static way.

**Comment by HaukeRa** [comment]
I haven't seen this behaviour previous to some refactoring, too. It just shows that an "unrelated" change can break something somewhere else. The Security.insertProviderAt method just does nothing if you install the same provider at the same position twice, so it should be safe to invoke it from the constructor of MeshManagerApi

**Comment by roshanrajaratnam** [comment]
Okies, let's go with the safer option then!
