### ISSUE TITLE
Expose attentionTimer as duration.

### ISSUE THREAD

**Issue by bangonkali** [NordicSemiconductor/Android-nRF-Mesh-Library#169]
**Is your feature request related to a problem? Please describe.**
In the iOS Version of the library it seems the [`attentionTimer` is exposed as `duration`](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/e2ce5afbb89b2200c659927d3634dd1c0a0bdba5/nRFMeshProvision/Classes/Provisioner/ProvisioningStates/InviteProvisioningState.swift#L26-L35).

```swift
    required init(withTargetNode aNode: UnprovisionedMeshNodeProtocol) {
        target                              = aNode
        duration                            = 0x05 //Default attention timer is 5 seconds
        super.init()
        target.basePeripheral().delegate    = self
        //If services and characteristics are already discovered, set them now
        let discovery                       = target.discoveredServicesAndCharacteristics()
        provisioningService                 = discovery.provisionService
        dataInCharacteristic                = discovery.dataInCharacteristic
        dataOutCharacteristic               = discovery.dataOutCharacteristic
    }
```

**Describe the solution you'd like**

Is it possible we also expose the same in Android library? It seems this one is [hard coded](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/a6857e47752cfc667e0601eca1f0bec6b8d97da0/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/MeshProvisioningHandler.java#L287-L294).

```
    private void sendProvisioningInvite(final UnprovisionedMeshNode unprovisionedMeshNode) {
        isProvisioningPublicKeySent = false;
        isProvisioneePublicKeyReceived = false;
        attentionTimer = 0x05;//0x0A;
        final ProvisioningInviteState invite = new ProvisioningInviteState(unprovisionedMeshNode, attentionTimer, mInternalTransportCallbacks, mStatusCallbacks);
        provisioningState = invite;
        invite.executeSend();
```

**Describe alternatives you've considered**

It would be interesting to make this user configurabl on the client side.

**Additional context**

`n/a`

**Comment by roshanrajaratnam** [comment]
@bangonkali this is correct and the attention timer will be exposed.

**Comment by roshanrajaratnam** [comment]
@bangonkali Fixed internaly
