### ISSUE TITLE
Sensor Client Model

### ISSUE THREAD

**Issue by michal-narajowski** [NordicSemiconductor/Android-nRF-Mesh-Library#17]
**Describe the solution you'd like**
I want to be able to access sensor data by sending commands to Sensor Server Model on another Mesh device. Things like reading Sensor descriptors, reading sensor values, etc.

**Comment by jakkra** [comment]
Hi, we are also looking for this, any plan on adding it? Is it a big task?

**Comment by roshanrajaratnam** [comment]
Hi @jakkra this is something in our backlog but will take some time due to some other priorities.

**Comment by roshanrajaratnam** [comment]
The latest version 3.1.5 of the library contains support for all Sensor messages and the sample app allows sending `SensorGet`.
