### ISSUE TITLE
Publishing address not working version 1.2.0

### ISSUE THREAD

**Issue by DevelopertwoAtBubblyNet** [NordicSemiconductor/Android-nRF-Mesh-Library#173]
---

**Describe the bug**
When I go to a client model and attempt to publish to an address the address does not stick once I tap apply. This just started happening on version 1.2.0. 
I believe it has something to do with addresses now being ints instead of byte arrays. 

**To Reproduce**
1. Go to Client model
2. Click on publish address (C888)
3. Type in address
4. click apply
5. New address does not stick

**Expected behavior**
The typed in publishing address should stick to the new configuration

**Platform details:**
 - Device:  OnePlus 6
 - OS: Android 9.0
 - Library Version 1.2.0

**Logs / Screenshots**
Android Studios says
"W/System.err: java.lang.IllegalArgumentException: Invalid publish address, publish address must be a 16-bit value"

**Comment by roshanrajaratnam** [comment]
@DevelopertwoAtBubblyNet Thanks for reporting this issue. I will send out a fix for this.
