### ISSUE TITLE
Generic level & on/off states for groups

### ISSUE THREAD

**Issue by SamS3lly** [NordicSemiconductor/Android-nRF-Mesh-Library#175]
When sending generic on/off and / or generic level messages to an element, current implementation requires a source address as well as a destination address, no matter what goes into the source address (e.g: Group address, Proxy unicast)
It will still control everything the same.

Should this happen, what is the correct source address we should use?

How should "group controls" work? whats the correct implementation on the provisioner? Can a provisioner act as a client to publish to group addresses?

**Platform details:**
 - Device: Android
 - OS: Android 7
 - Library Version: 1.2.0

**Comment by roshanrajaratnam** [comment]
Hi @SamS3lly , this is up to the user, you can use a group address or a unicast address depending on what your destination is. If you want to send a message to a group, use a group address as the source or unicast address if you are sending it to the model itself.

Also we would prefer opening a new issue for a newer question but i will answer it here for now. When you subscribe an model to a group address you will see all the models that subscribed to a group listed in the groups view. You can control(on/off or send vendor model messages) the groups from this view. What do you mean what's the correct implementation on the provisioner? a provisioner is a node just like every other node in a network with provisioning capabilities. You may publish to a group address from the the provisioner. This is how the app behaves as of now when sending group messages or on/off/level messages to unicast addresses.
