### ISSUE TITLE
Publish Period settings do not work

### ISSUE THREAD

**Issue by kcjian** [NordicSemiconductor/Android-nRF-Mesh-Library#178]
![321551864653_ pic](https://user-images.githubusercontent.com/15611112/53872766-defdcf80-4039-11e9-9585-a9a004f0ab4a.jpg)

 hi，according to the Mesh protocol I think
 **int period=(resolution << 6) | steps ;**
but in the [ConfigModelPublicationSet.java]( https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/master/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/transport/ConfigModelPublicationSet.java),Line 185
**paramsBuffer.put((byte) ((publicationSteps << 6) | publicationResolution));**
I hope you can have a look.

**Platform details:**
 - Library Version 1.2.1

**Comment by roshanrajaratnam** [comment]
@kcjian Thanks for reporting this. It is broken!

**Comment by kcjian** [comment]
I found this problem in many places, such as SceneRecall,GenericOnOffSet, looking forward to your updates.

**Comment by roshanrajaratnam** [comment]
I have merged this to dev branch now and it should work for you!

**Comment by kcjian** [comment]
@roshanrajaratnam Thank you ~
