### ISSUE TITLE
Segment received is from a different src than the one we are processing, let's drop it

### ISSUE THREAD

**Issue by WangManAndroid** [NordicSemiconductor/Android-nRF-Mesh-Library#197]
i got problem, 
05-08 19:18:04.253 16867-16882/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Dst: 0x7FFF
05-08 19:18:04.253 16867-16882/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Received a segmented access message from: 0032
05-08 19:18:04.253 16867-16882/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: current unicastAddress: 0031
05-08 19:18:04.253 16867-16882/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Segment received is from a different src than the one we are processing, let's drop it
  
for example： our device  had  two elements and their address is, 0x0031 0x0032  ,wen i  Read State from 0x0031 is all right,but  wen i Read State From 0x0032  problem happend  above

**Comment by ximplarandy** [comment]
This potentially is the same issue that I am facing?

**Comment by WangManAndroid** [comment]
android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "no.nordicsemi.android.nrfmeshprovisioner"
        minSdkVersion 18
        targetSdkVersion 28
        versionCode 29
        versionName "1.2.1"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }

    dexOptions {
        preDexLibraries = false
    }

    configurations.all {
        resolutionStrategy.force 'com.android.support:multidex:1.0.2'
    }
}

**Comment by roshanrajaratnam** [comment]
closing issue in favour of #196
