### ISSUE TITLE
Provisioning the second Thingy will failed

### ISSUE THREAD

**Issue by kcjian** [NordicSemiconductor/Android-nRF-Mesh-Library#20]
---

**Describe the bug**
Provisioning the second Thingy will failed，happen to Example/nrf-mesh 1.0

**To Reproduce**
1. Provisioning a Thingy,Succeed
2. Provisioning the second Thingy , Failed always

**Comment by roshanrajaratnam** [comment]
Hi, sorry for the inconvenience, I just noticed this issue and I'll look in to it soon. what's  the fw you have used on the Thingy? Any chance you could provide it, if its a custom fw?

**Comment by roshanrajaratnam** [comment]
@kcjian any updates on this issue? Was there some kind of an error that was thrown while provisioning the second thingy? What fw did you use for this? If its a custom fw any chance you could share it with me?

**Comment by kcjian** [comment]
Thank you for your reply, I thought i solved this problem by modifying the file MeshService.java
![2018-07-24 4 41 44](https://user-images.githubusercontent.com/15611112/43128608-fa67897c-8f64-11e8-98a1-d64800bbb3c3.png)

**Comment by roshanrajaratnam** [comment]
Great thanks!
