### ISSUE TITLE
'sendGenericOnOffGet' doesn't call 'updateMeshMessage' when invoked from onCreate

### ISSUE THREAD

**Issue by MeenalBahua** [NordicSemiconductor/Android-nRF-Mesh-Library#203]
---

When i tried to invoke sendGenericOnOffGet from onCreate method in GenericOnOffServerActivity. it never invokes updateMeshMessage. If we invoke sendGenericOnOffGet through a click event it works fine. During debug or if i add some delay before invoking the the get call, it works fine. What could be the possible reason for this behaviour?

**Comment by roshanrajaratnam** [comment]
@MeenalBahua may be you send this before the observer is set up the observer?

**Comment by MeenalBahua** [comment]
No, Observer is called in the base class (BaseModelConfigurationActivity) itself.

**Comment by roshanrajaratnam** [comment]
Yes that's right, However have you checked if you get a reply from the device at all?

**Comment by MeenalBahua** [comment]
Yes, We do receive reply from the device, and i traced its path till 'parseNotifications' in MeshManagerApi. It also But after this it looses its reference. 'parseMeshMsgNotifications' from BaseMeshMessageHandler never gets called. The 'unsegmentedPdu' is of the type 'PDU_TYPE_NETWORK', so it enters the correct switch case as well.

**Comment by MeenalBahua** [comment]
Resolved it. There was issue due to multiple observers for same SingleLiveData object.

**Comment by roshanrajaratnam** [comment]
Great, was this happenning in the original app or did it happen after your changes?

**Comment by MeenalBahua** [comment]
Yes. To reproduce it, call the get method from onCreate in any of the model activities. The observer callback goes to previous activity (nodeconfiguration) instead of the model activity(like GenericOnOffActivity). I changed mMeshMessageLiveData in NrfMeshRepository from SingleLiveEvent to MutableLiveData.

**Comment by roshanrajaratnam** [comment]
Right I see, but making it mutable live data will notify all observers including the nodeConfiguration and also will update every time you rotate the screen. May be you can remove the observer onStop() and set it again in onStart()

**Comment by MeenalBahua** [comment]
Ok, OnStop gets called a little after next activity's OnCreate. OnPause was a better place to remove observer.
