### ISSUE TITLE
Provisioning  public key received...  

### ISSUE THREAD

**Issue by WangManAndroid** [NordicSemiconductor/Android-nRF-Mesh-Library#205]
`06-15 12:57:23.670 25972-25983/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=38:D2:CA:03:07:11 UUID=00002adb-0000-1000-8000-00805f9b34fb Status=0
06-15 12:57:23.670 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0x03020000000000
06-15 12:57:23.670 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Provisioning pdu sent: 0x03020000000000
06-15 12:57:23.690 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/ProvisioningPublicKeyState: X: length: 32 13731413D22B8707AD9609A9FC097A2B10E81C705AF67F019BE752FBD65C9FB9
06-15 12:57:23.690 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/ProvisioningPublicKeyState: Y: length: 32 9CC2DE08289EFAB95CE81AD38381AC380896351D0FD224D0DF726F4C6B82B784
06-15 12:57:23.690 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/ProvisioningPublicKeyState: XY: 0x13731413D22B8707AD9609A9FC097A2B10E81C705AF67F019BE752FBD65C9FB99CC2DE08289EFAB95CE81AD38381AC380896351D0FD224D0DF726F4C6B82B784
06-15 12:57:23.690 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0x430313731413D22B8707AD9609A9FC097A2B10E8
06-15 12:57:23.690 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0x831C705AF67F019BE752FBD65C9FB99CC2DE0828
06-15 12:57:23.700 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0x839EFAB95CE81AD38381AC380896351D0FD224D0
06-15 12:57:23.700 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0xC3DF726F4C6B82B784
06-15 12:57:23.700 25972-25983/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002adb-0000-1000-8000-00805f9b34fb
06-15 12:57:23.700 25972-25972/no.nordicsemi.android.nrfmeshprovisioner D/MeshAutoProvisionerActivity: setupProvisionerStateObservers: PROVISIONING_PUBLIC_KEY_SENT
06-15 12:57:23.700 25972-26054/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=38:D2:CA:03:07:11 UUID=00002adb-0000-1000-8000-00805f9b34fb Status=0
06-15 12:57:23.700 25972-26054/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0x430313731413D22B8707AD9609A9FC097A2B10E8
06-15 12:57:23.700 25972-26054/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002adb-0000-1000-8000-00805f9b34fb
06-15 12:57:23.700 25972-25984/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=38:D2:CA:03:07:11 UUID=00002adb-0000-1000-8000-00805f9b34fb Status=0
06-15 12:57:23.700 25972-25984/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0x831C705AF67F019BE752FBD65C9FB99CC2DE0828
06-15 12:57:23.700 25972-25984/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002adb-0000-1000-8000-00805f9b34fb
06-15 12:57:23.700 25972-26054/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=38:D2:CA:03:07:11 UUID=00002adb-0000-1000-8000-00805f9b34fb Status=0
06-15 12:57:23.700 25972-26054/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0x839EFAB95CE81AD38381AC380896351D0FD224D0
06-15 12:57:23.700 25972-26054/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002adb-0000-1000-8000-00805f9b34fb
06-15 12:57:23.710 25972-25983/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=38:D2:CA:03:07:11 UUID=00002adb-0000-1000-8000-00805f9b34fb Status=0
06-15 12:57:23.710 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0xC3DF726F4C6B82B784
06-15 12:57:23.710 25972-25983/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Provisioning pdu sent: 0x030313731413D22B8707AD9609A9FC097A2B10E81C705AF67F019BE752FBD65C9FB99CC2DE08289EFAB95CE81AD38381AC380896351D0FD224D0DF726F4C6B82B784
06-15 12:57:23.890 25972-26132/no.nordicsemi.android.nrfmeshprovisioner D/dalvikvm: GC_FOR_ALLOC freed 2345K, 17% free 16872K/20120K, paused 47ms, total 47ms
06-15 12:57:23.890 25972-25984/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=38:D2:CA:03:07:11 UUID=00002adc-0000-1000-8000-00805f9b34fb
06-15 12:57:23.890 25972-25984/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0x03035164392BD48D4DC18BC0C6ADCA52611EFE60
06-15 12:57:23.890 25972-25984/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Received provisioning message: 0x03035164392BD48D4DC18BC0C6ADCA52611EFE60
06-15 12:57:23.890 25972-25972/no.nordicsemi.android.nrfmeshprovisioner D/MeshAutoProvisionerActivity: setupProvisionerStateObservers: PROVISIONING_PUBLIC_KEY_RECEIVED
06-15 12:57:23.890 25972-25984/no.nordicsemi.android.nrfmeshprovisioner W/BluetoothGatt: Unhandled exception in callback
    java.lang.ArrayIndexOutOfBoundsException: src.length=18 srcPos=0 dst.length=32 dstPos=0 length=32
        at java.lang.System.arraycopy(Native Method)
        at no.nordicsemi.android.meshprovisioner.provisionerstates.ProvisioningPublicKeyState.generateSharedECDHSecret(ProvisioningPublicKeyState.java:151)
        at no.nordicsemi.android.meshprovisioner.provisionerstates.ProvisioningPublicKeyState.parseData(ProvisioningPublicKeyState.java:94)
        at no.nordicsemi.android.meshprovisioner.MeshProvisioningHandler.parseProvisioneePublicKeyXY(MeshProvisioningHandler.java:458)
        at no.nordicsemi.android.meshprovisioner.MeshProvisioningHandler.parseProvisioningNotifications(MeshProvisioningHandler.java:118)
        at no.nordicsemi.android.meshprovisioner.MeshManagerApi.parseNotifications(MeshManagerApi.java:384)
        at no.nordicsemi.android.meshprovisioner.MeshManagerApi.handleNotifications(MeshManagerApi.java:337)
        at no.nordicsemi.android.nrfmeshprovisioner.viewmodels.NrfMeshRepository.onDataReceived(NrfMeshRepository.java:477)
        at no.nordicsemi.android.nrfmeshprovisioner.ble.BleMeshManager$1.onCharacteristicNotified(BleMeshManager.java:180)
        at no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.onCharacteristicChanged(BleManager.java:1444)
        at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:419)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:403)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)`

**Comment by WuLFGit** [comment]
Hi @WangManAndroid ,

i have the same issue when trying to provision. Could you please explain what was the problem for you and how did you resolve?

Thank you in advance!
