### ISSUE TITLE
Importing network can't bind key config model

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/Android-nRF-Mesh-Library#208]
---

**Describe the bug**
After importing a network from another device, unable to bind key or publish.

**To Reproduce**
1. Export network
2. Import network on new device
3. Navigate to configuration model

**Expected behavior**
Ability to bind key to configuration model after importing a network.

**Platform details:**
 - Device: Galaxy Tab S5E
 - OS: Android 9.0
 - Library Version (dev branch)

**Logs / Screenshots**

![Screenshot_20190626-171108_BubblyNet](https://user-images.githubusercontent.com/47896433/60215670-1df8a080-9836-11e9-891e-b62e138c4068.jpg)

**Comment by roshanrajaratnam** [comment]
Hi, you cannot bind a key to a configuration server.
