### ISSUE TITLE
Unable to bind configuration server

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/Android-nRF-Mesh-Library#209]
---

**Describe the bug**
Unable to bind key to configuration server 

**To Reproduce**
1. Go to configuration server
2. Click on bind key

**Expected behavior**
Ability to bind key

**Platform details:**
 - Device: Galaxy Tab S5E
 - OS: Android 9.0
 - Library Version (dev and master branches)

**Logs / Screenshots**
![Screenshot_20190626-172009_nRF Mesh](https://user-images.githubusercontent.com/47896433/60216042-05d55100-9837-11e9-8d71-f76a58892376.jpg)

**Comment by roshanrajaratnam** [comment]
Hi, you cannot bind a key to a configuration server.
