### ISSUE TITLE
Example mesh firmware for nRF52840

### ISSUE THREAD

**Issue by vanbako** [NordicSemiconductor/Android-nRF-Mesh-Library#21]
Hello,

Can you add example mesh firmware for nRF52840?

Thanks

**Comment by roshanrajaratnam** [comment]
Hi, you may find this in the latest mesh sdk release [2.1.1](https://www.nordicsemi.com/eng/nordic/Products/nRF52832/nRF5-SDK-for-Mesh/62721) in the bin\merged\ospace\examples since the 2.1.0 did not have the pre-built hex files.
