### ISSUE TITLE
Question: Min SDK 

### ISSUE THREAD

**Issue by BubblyNetDev** [NordicSemiconductor/Android-nRF-Mesh-Library#211]
Hey,

Was wondering if there would be any issues increasing the min SDK to 21?

**Comment by roshanrajaratnam** [comment]
We prefer supporting all devices that supports bluetooth low energy (sdk 18 and onwards). AFAIK, I don't think you are allowed to have two different min sdk versions in the app and the library. Therefore you'll have to update this in your own implementation (both app and lib) and I don't think it should be a problem.

**Comment by BubblyNetDev** [comment]
Sounds good, thank you.
