### ISSUE TITLE
error 133

### ISSUE THREAD

**Issue by xiaofengming** [NordicSemiconductor/Android-nRF-Mesh-Library#217]
133 error when identifyNode and startProvisioning ?

**Comment by dev-sareno** [comment]
Similar to [this one](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/issues/214#issue-469830873).

**Comment by xiaofengming** [comment]
What is your solution?

**Comment by dev-sareno** [comment]
I upgraded the BLE library from 1.2.0 to 2.1.1 as i mentioned [here](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/issues/214#issuecomment-515857878). It doesn't totally fixed the solution but however it lessen the occurrence of 133 error.

**Comment by xiaofengming** [comment]
Execute this getNrfMeshRepository().getBleMeshManager().refreshDeviceCache();  before connecting

but it reduced the occurrence of 133 errors.

**Comment by roshanrajaratnam** [comment]
@xiaofengming This is already done during every disconnect. Also @dev-sareno the reason for BLE library version 2.1.1 lessens this issue is that it has a retry mechanism implemented.

**Comment by xiaofengming** [comment]
Version 2.1.1 is not compatible with your library

**Comment by roshanrajaratnam** [comment]
@xiaofengming yes it's in the backlog to be added

**Comment by zhangping001** [comment]
mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                ConnectRequest connectRequest = mBleMeshManager.connect(bluetoothDevice);
               // mBleMeshManager.internalConnect(bluetoothDevice,connectRequest);//private method !!!!!
            }
        },1000);

in lib 2.1.1,Internal private method, how to connect BLE?

**Comment by dev-sareno** [comment]
> ```
>     mHandler.postDelayed(new Runnable() {
>         @Override
>         public void run() {
>             ConnectRequest connectRequest = mBleMeshManager.connect(bluetoothDevice);
>            // mBleMeshManager.internalConnect(bluetoothDevice,connectRequest);//private method !!!!!
>         }
>     },1000);
> ```
> 
> in lib 2.1.1,Internal private method, how to connect BLE?

You have to call `connectRequest.enqueue()` for async or  `connectRequest.await()` for sync call.
