### ISSUE TITLE
List of Changes in latest merge in master

### ISSUE THREAD

**Issue by MeenalBahua** [NordicSemiconductor/Android-nRF-Mesh-Library#238]
Hi,

I can some visible changes (like code review and bug fixes) in the latest Master branch. But, can you please list down anything specific or major changes or fix which will help in understanding the latest code merge.

Thank you.

**Comment by roshanrajaratnam** [comment]
Hi the summary of changes are listed here #227. Hop this helps

**Comment by MeenalBahua** [comment]
Yes. It definitely helps. Thank you.
