### ISSUE TITLE
hello，Messages always accept errors

### ISSUE THREAD

**Issue by xiaofengming** [NordicSemiconductor/Android-nRF-Mesh-Library#239]
DefaultNoOperationMessageState: Message reassembly may not be completed yet!

**Comment by roshanrajaratnam** [comment]
Hi sorry about this, could you elaborate the issue please?

**Comment by xiaofengming** [comment]
not solved ！ The message can be done, but I think the return data is too slow，
I want to accept the message quickly.

**Comment by WangManAndroid** [comment]
我的用的就很正常啊  你是哪家公司？

**Comment by WangManAndroid** [comment]
你看看是否是你们硬件协议栈问题    我用的就很正常

**Comment by xiaofengming** [comment]
深圳一家公司，循环设置ConfigModel 类的消息（比如BoundAppKey ，PublicationSet），你有收不到的情况吗？

**Comment by WangManAndroid** [comment]
> 我的用的就很正常啊 你是哪家公司？
正常的ConfigMessage  GenericMessage 都会在150+（50*TTL）ms  收到，如果经常收不到你的抓包看看了，很有可能是你们硬件协议栈问题。我这边也会有时收不到相应的Status，但是很少很少。

**Comment by WangManAndroid** [comment]
case MeshManagerApi.PDU_TYPE_NETWORK:

                    //This is not possible however let's return null
                    if (provisionerAddress == null) {
                        return null;
                    }

                    //Check if the message is directed to us, if its not ignore the message
                    if (provisionerAddress != dst) {
                        Log.v(TAG, "Received a control message that was not directed to us, so we drop it");
                        return null;
                    }

                    if (isSegmentedMessage(decryptedNetworkPayload[2])) {
                        return parseSegmentedControlMessage(data, decryptedProxyPdu, ttl, src, dst);
                    } else {
                        return parseUnsegmentedControlMessage(data, decryptedProxyPdu, ttl, src, dst, sequenceNumber);
                    }



这是最新的代码  你看看跟你的是否不同  NetWorkLayer

**Comment by xiaofengming** [comment]
Gatt链接的设备木有回不来情况，周围mesh设备config类型消息很大概率回不来

**Comment by xiaofengming** [comment]
@roshanrajaratnam hello，The mesh device is not a gatt device, and there is always a situation where ConfigMessage cannot receive it.

**Comment by roshanrajaratnam** [comment]
Hi @xiaofengming what do you mean by the mesh device is not a gatt device? If the device supports the Mesh Provisioning Service and Proxy Service it will can communicate over the GATT bearer. Currently our sample application does not have the Advertising bearer implemented. The users of this library are welcome to implement their own advertising bearer and use the library as it is. Hope this answers your question :)

**Comment by xiaofengming** [comment]
@roshanrajaratnam The proxy device will not accept the ConfigMessage failure. The device forwarded by the proxy will accept the ConfigMessage failure, not 100%, but it is very frequent.

**Comment by roshanrajaratnam** [comment]
@xiaofengming have you checked the TTL to make sure if the message can reach the end device via the proxy?

**Comment by xiaofengming** [comment]
globalTtl = 5 ，node  publishTtl =16；

**Comment by WangManAndroid** [comment]
@xiaofengming   这个你得debug,然后发现问题，定位问题原因，我怀疑你们硬件mesh 协议栈问题，我现在开发就用的这个nordic 的demo，有小bug ，有些硬件协议栈实现问题，你得仔细debug,我也是一步一步摸索出来的，最总都能定位是什么问题，都能解决。
