### ISSUE TITLE
 How  we  deal with IV Update procedure?

### ISSUE THREAD

**Issue by WangManAndroid** [NordicSemiconductor/Android-nRF-Mesh-Library#244]
if  Sequence Number = 16777216    what  should   i do?

**Comment by roshanrajaratnam** [comment]
@WangManAndroid Currently we don't support the IV Update procedure yet. We will add this sometime soon

**Comment by WangManAndroid** [comment]
@roshanrajaratnam    well  got  it

**Comment by BubblyNetDev** [comment]
Hello, I was wondering if there is any update on this feature, and when we could expect it?

**Comment by roshanrajaratnam** [comment]
Hi unfortunately we have some other priorities so this feature will take some time to be implemented, not sure when though.

**Comment by WangManAndroid** [comment]
hi @roshanrajaratnam  How is this going? I am anxious to deal with this
