### ISSUE TITLE
BaseMeshMessageHandler sequence numbers not properly checked

### ISSUE THREAD

**Issue by HaukeRa** [NordicSemiconductor/Android-nRF-Mesh-Library#245]
---

**Describe the bug**
Duplicate messages are not ignored. The sequence number is effectively only checked if it has the right format. If that is the case it is always accepted, even if it is the same as the last packet or even older.

**To Reproduce**
While this doesn't happen with a GATT bearer, because the proxy will probably never pass duplicate messages, it happens with an Advertising bearer. To simulate this, one can double all messages received by the GATT bearer and check, that the duplicates are not ignored.

**Expected behavior**
Mesh messages with an older or equal sequence number must be ignored.

Here an else branch with return null; is required:
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/b6d32cb97a2212f3dfe574ee093b93fafe7da752/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/transport/BaseMeshMessageHandler.java#L131

**Comment by roshanrajaratnam** [comment]
@HaukeRa thanks for reporting this, it indeed is a nice catch.
