### ISSUE TITLE
Failed to send message to node after importing network

### ISSUE THREAD

**Issue by NIUNIUN** [NordicSemiconductor/Android-nRF-Mesh-Library#248]
---

**Describe the bug**
With the export/import network feature, a message cannot be sent to a node after the network is imported.

**Platform details:**
 - Device: Replay: src 0x0001 dst 0xc000 seq 0x00009c.

**Logs / Screenshots**
![image](https://user-images.githubusercontent.com/24909712/65398170-546b9a80-dde8-11e9-8d2b-5e3f311952da.png)

**Comment by WangManAndroid** [comment]
看这个消息应该是分组消息，你看看蓝牙硬件打印,调试一下

**Comment by WangManAndroid** [comment]
@NIUNIUN   你试试看改一下src地址，有可能是重放保护了

**Comment by roshanrajaratnam** [comment]
@NIUNIUN After exporting make sure you change the provisiner address as the sequence numbers are not shared the messages sent from the same address on a different phone will fail.

**Comment by NIUNIUN** [comment]
@roshanrajaratnam thank you!

**Comment by roshanrajaratnam** [comment]
@NIUNIUN You're welcome!
