### ISSUE TITLE
Please update the README.md

### ISSUE THREAD

**Issue by warpfuturechina** [NordicSemiconductor/Android-nRF-Mesh-Library#253]
1. When I read the readme document, I found some incorrect keyword description when comparing with the project file or folder. If you can, fix and update the documentation, thanks!
2. The project documents and library lack more descriptions, so I don't know how they are used and how to integrate them.

**Comment by roshanrajaratnam** [comment]
@warpfuturechina nice catch, yes looks like the readme was not updated for a while. I'll fix it soon.

**Comment by roshanrajaratnam** [comment]
Sorry for not taking up this earlier, will update this shortly.
