### ISSUE TITLE
What's the next step after : `public void onScanResult(int callbackType, final ScanResult result) ` in Android

### ISSUE THREAD

**Issue by xxfenxx** [NordicSemiconductor/Android-nRF-Mesh-Library#255]
### meshprovisioner library integration

While the code recevied callback `public void onScanResult(int callbackType, final ScanResult result) ` in Android, I did not know what is the next step（isMeshBeacon）.

**Now I guess：**

1、check Whether or not it a mesh beacon device
2、create a UnprovisionedMeshNode like iOS ? But the UnprovisionedMeshNode  structure function really confuse me.

**And compareing with the iOS , I should create a UnprovisionedMeshNode and connecting to it blePeripheral :** 

**Firstly:**
`
let newNode = UnprovisionedMeshNode(withPeripheral: peripheral,
                                            andAdvertisementDictionary: advertisementData,
                                            RSSI: RSSI)
`

**Secondy:**
`
private func connectNode(_ aNode: UnprovisionedMeshNode) {
        targetUnprovisionedNode = aNode
        centralManager.delegate = self
        centralManager.connect(targetUnprovisionedNode.blePeripheral(), options: nil)
        targetUnprovisionedNode.logDelegate?.logConnect()
    }
`

**The third**

1、start provisoning the UnprovisionedMeshNode and completed.
      detail ...
2、disconnect to the UnprovisionedMeshNode
     detail ...
3、start provisoning ProvisionedMeshNode and completed.
     detail ...

**My question is : While the code recevied callback in `onScanResult ` in Android next step is ?** 

**PS: Maybe there should update a document about how to use the `meshprovisioner ` library, thanks !**

**Comment by roshanrajaratnam** [comment]
Hi sorry for any inconvenience caused. We will soon be preparing some more documentation. However, in order to provision a node you connect to the node, call identify and then call provision. You don't need to create an unprovisioned node yourself. You may also refer the sample Android app.
