### ISSUE TITLE
the isValidUnassignedAddress() method is incorrect

### ISSUE THREAD

**Issue by xiaofengming** [NordicSemiconductor/Android-nRF-Mesh-Library#257]
@roshanrajaratnam 
/**
     * Validates an unassigned address
     *
     * @param address 16-bit address
     * @return true if the address is a valid unassigned address or false otherwise
     */
    public static boolean isValidUnassignedAddress(@NonNull final byte[] address) {
        if (isAddressInRange(address)) {
            return false;
        }
        return isValidUnassignedAddress(MeshParserUtils.unsignedBytesToInt(address[0], address[1]));
    }

--------------------Should be changed

/**
     * Validates an unassigned address
     *
     * @param address 16-bit address
     * @return true if the address is a valid unassigned address or false otherwise
     */
    public static boolean isValidUnassignedAddress(@NonNull final byte[] address) {
        if (!isAddressInRange(address)) {
            return false;
        }
        return isValidUnassignedAddress(MeshParserUtils.unsignedBytesToInt(address[0], address[1]));
    }

**Comment by roshanrajaratnam** [comment]
Nice catch, I'll be out of work for the next 2 weeks and will fix when I am back. Also free to contribute towards by sending us a pull request :) l

**Comment by tayyars** [comment]
also :
 Lower transport layer has values in big endian byte order, not little endian

**Comment by roshanrajaratnam** [comment]
@tayyars according the mesh specification 1.0.1 section 3.5.1 "All multiple-octet numeric values in this layer shall be sent in “big endian”, as described in Section 3.1.1.1" in the lower transport layer.

**Comment by tayyars** [comment]
> @tayyars according the mesh specification 1.0.1 section 3.5.1 "All multiple-octet numeric values in this layer shall be sent in “big endian”, as described in Section 3.1.1.1" in the lower transport layer.

 /**
     * Validates a unicast address
     *
     * @param address Address in bytes
     * @return true if the address is a valid unicast address or false otherwise
     */
    public static boolean isValidUnicastAddress(@NonNull final byte[] address) {
        if (!isAddressInRange(address)) {
            return false;
        }

        return isValidUnicastAddress(**MeshParserUtils.unsignedBytesToInt(address[0], address[1]**));
    }

 /**
     * Convert signed bytes to a 16-bit unsigned int.
     */
    public static int unsignedBytesToInt(byte b0, byte b1) {
        **return (unsignedByteToInt(b0) + (unsignedByteToInt(b1) << 8));**
    }

Should be ->
  **return (unsignedByteToInt(b0) << 8) + unsignedByteToInt(b1);** 

or i miss something ?

**Comment by roshanrajaratnam** [comment]
The validation was wrong because of a missing `!` when checking if the address is in range. So in my humble opinion the current implementation is correct.

**Comment by xiaofengming** [comment]
@roshanrajaratnam LowerTransportLayer.class 

------final int blockAckSrc = MeshParserUtils.unsignedBytesToInt(dst[1], dst[0]);----
and 
------MeshAddress.isValidUnicastAddress(dst)

return isValidUnicastAddress(**MeshParserUtils.unsignedBytesToInt(address[0], address[1]**));-----

There will always be a verification address
