### ISSUE TITLE
Hi Warmly Team 

### ISSUE THREAD

**Issue by theanhbp2018** [NordicSemiconductor/Android-nRF-Mesh-Library#258]
---
Hello
we can't provisioning with devices that have more than 2 elements, do you have plan in order to fix them ? 

thanks

**Comment by roshanrajaratnam** [comment]
Hi which nRF Mesh SDK version are you referring to? Could you provide some more information please?

**Comment by theanhbp2018** [comment]
applicationId "no.nordicsemi.android.nrfmeshprovisioner"
        minSdkVersion 18
        targetSdkVersion 29
        versionCode 53
        versionName "2.0.5"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

above is some info I used them,

**Comment by roshanrajaratnam** [comment]
Hi, how about the nRF Mesh SDK version? Have you tested with some of the examples available in the sdk?

**Comment by tayyars** [comment]
Hi ,
there a bug in isValidUnassignedAddress()
causing this problem.
#257

**Comment by theanhbp2018** [comment]
> 
> 
> Hi, how about the nRF Mesh SDK version? Have you tested with some of the examples available in the sdk?

I used SDK 3.2.0.

**Comment by theanhbp2018** [comment]
> Hi ,
> there a bug in isValidUnassignedAddress()
> causing this problem.
> #257

how I can fix them ?

**Comment by roshanrajaratnam** [comment]
Hi, I'm currently out of office at the moment. I'll be back at work next week and I'll have a look at it. If you think 'isValidUnassignedAddress()' is causing the issue, check the comment from xiaofengming on #257 and try this

**Comment by roshanrajaratnam** [comment]
@theanhbp2018 What's the nRF Mesh SDK version you are using on the firmware side?

**Comment by roshanrajaratnam** [comment]
@theanhbp2018 Sorry for the delay I will take a look at this.

**Comment by roshanrajaratnam** [comment]
@theanhbp2018 check out the fix on the following [branch](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/compare/bugfix/large-composition-data-get-failure)

**Comment by theanhbp2018** [comment]
thank you guys
