### ISSUE TITLE
Timestamp in TAI

### ISSUE THREAD

**Issue by bangonkali** [NordicSemiconductor/Android-nRF-Mesh-Library#262]
---

**Describe the bug**
It seems that the timestamp was changed in Dev branch where it no longer needs an offset. Is this intentional with the move to AndroidX or with the support of Import/Export with iOS Nordic V2?

Of particular interest is the following pull request https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/pull/261/commits/83875dc0f9e89f3471314bc9ee70289dc405011b 

This line exactly had an offset before: 

https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/1840c9da20d90a8879aa677e9373fd376e0c3f80/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/MeshManagerApi.java#L1033

by: 

https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/1840c9da20d90a8879aa677e9373fd376e0c3f80/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/utils/MeshParserUtils.java#L573-L586

We propose offsetting the time with `TAI_OFFSET = 946598400000L;` for both `iOS` and `Android`. 

As per Mesh Model Bluetooth® Specification 5.1.1.1 Revision: v1.0.1. The TAI Seconds state is the current TAI time in seconds after the epoch 2000-01-01T00:00:00 TAI (1999-12-31T23:59:28 UTC). Epoch 946598400000L UTC is roughly equivalent to TAI offset, a simple approximation. 

Where 946598400000L being the result of the following calculation:
```
       final Calendar calendar = Calendar.getInstance();
       calendar.set(2000, 0, 0, 0, 0, 0);
       calendar.set(Calendar.MILLISECOND, 0);
       final long millisSinceEpoch = calendar.getTimeInMillis();
```

If the intention is to no longer support offsetting, please close/ignore the PR https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/pull/261/commits/83875dc0f9e89f3471314bc9ee70289dc405011b. Thanks!

**Comment by roshanrajaratnam** [comment]
Hi @bangonkali, currently I'm out of office. I'll take a look at it when I am back. If I recall correctly TAI should have been completely removed from the mesh network JSON file. I think I might have missed this while refactoring. Thanks for pointing this.
