### ISSUE TITLE
Device cache not refreshed after device is reset

### ISSUE THREAD

**Issue by BleonDev** [NordicSemiconductor/Android-nRF-Mesh-Library#270]
After the first Provisioning succeeds; Then, Reset Node and start Provisioning for the second time. APP uses   "Proxy Service"  for Provisioning. At this point, we need to restart bluetooth for Provisioning. 
  
**Logs / Screenshots**
**step1**:After Provisioning succeeds for the first time, we will Reset Node in APP.
![reset_dev1](https://user-images.githubusercontent.com/46095566/68524150-34dbf300-02fe-11ea-946f-3e4acd09fe3b.png)

**step2**:Then a second Provisioning, when the app is Provisioning with Proxy Service instead of Proxy Service 
![1111](https://user-images.githubusercontent.com/46095566/68524242-7620d280-02ff-11ea-8828-b0d9cea4d48a.png)；Then there is provisioning Service on the device, not proxy Servce  
![61573278705_ pic](https://user-images.githubusercontent.com/46095566/68524276-c0a24f00-02ff-11ea-8899-6152066292f9.jpg)

**step2**: We need to reopen bluetooth for Provisioning
![2222](https://user-images.githubusercontent.com/46095566/68524298-fe9f7300-02ff-11ea-804d-5c59494c313c.png)

Thank you.

**Comment by philips77** [comment]
It's a caching issue. The library forces clearing the cache after provisioning, but not after resetting. It's a room for improvement.

**Comment by BleonDev** [comment]
> It's a caching issue. The library forces clearing the cache after provisioning, but not after resetting. It's a room for improvement.

invoke refreshDeviceCache after provisioning,and refreshDeviceCache return is true; but next provisioning still use "proxy service"
![bug02](https://user-images.githubusercontent.com/46095566/68555469-e860f680-0468-11ea-8d45-6c02283adb92.png)
