### ISSUE TITLE
Ask a question - how to know the device online status?

### ISSUE THREAD

**Issue by cjeyouni** [NordicSemiconductor/Android-nRF-Mesh-Library#275]
When the Device offLine,It didn't report。

**Comment by roshanrajaratnam** [comment]
Currently only the correct/disconnect button will notify the connected/disconnected state to a proxy node.

**Comment by cjeyouni** [comment]
There is something wrong with my question。Change the question，A device is close，the other device how to report A off state。with the Publish Address?,or other method?

**Comment by roshanrajaratnam** [comment]
No problem. Yes you can set publishing.

**Comment by cjeyouni** [comment]
thanks
