### ISSUE TITLE
Automatic Connection

### ISSUE THREAD

**Issue by 4smartiot** [NordicSemiconductor/Android-nRF-Mesh-Library#280]
I saw in iOS App had been new function can able to connect by Proxy, I thought should do that in android App. You can think more.

thanks

**Comment by roshanrajaratnam** [comment]
Do you mean automatically connect to proxies in range? Yes this is something that can be added.

**Comment by theanhbp2018** [comment]
I am here waiting for you

**Comment by roshanrajaratnam** [comment]
Hi @theanhbp2018 unfortunately this is not something we will do right now due to some other priorities but will make sure to add this down the line.

**Comment by DevHachi** [comment]
I wanted to ask. If there is any progress to that. Cause I would also like to have this functionality this would reduce significally the amount of work to do this myself.

**Comment by roshanrajaratnam** [comment]
Hi, we have not done any work on this and will have to wait due to some other priorities.

**Comment by Fabbros** [comment]
@roshanrajaratnam I'm also interested in this point. I understand that this is scheduled sometime soon, but can you get me a pointer to something useful to build something custom by myself?

**Comment by roshanrajaratnam** [comment]
Hi, I'm out of office at the moment, however you could take a look at the scanning and connection functionality  ScannerRepository class. You could write your own function based on this to connect automatically on app startup. Hope this helps.
