### ISSUE TITLE
Generic Level's Move: Remaining time issue

### ISSUE THREAD

**Issue by vikrant8051** [NordicSemiconductor/Android-nRF-Mesh-Library#282]
When Gen. Level's Move is in progress & Client sends level get command
then even when NODE send Remaining time as 0x3F in response, nRFMesh 
App shows Remaining Time as 6300 ms.

In this case, Rem Time should be display as "UNKWOWN"

**Comment by roshanrajaratnam** [comment]
I think this might need to be reported [here](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library) as currently Android version does not support Generic Level Move.

**Comment by vikrant8051** [comment]
Even though Move (which is related to Gen. Level state) is not supported kindly note that
Gen. Level could bounded with any other states (like Gen. OnOff, Light Lightness , Light CTL)

In that case, when client will ask status (when MOVE is in progress) via 
 - gen. onoff get or
- gen, level get
- light lightness actual get or
- light ctl get
then here remaining time should get as "Unknown"
