### ISSUE TITLE
Lists only two provisioned devices in Network tab

### ISSUE THREAD

**Issue by hardiksingh-rathore** [NordicSemiconductor/Android-nRF-Mesh-Library#284]
---

**Describe the bug**
- If I provision three mesh nodes (A,B and C), the app list only the last two devices(it's A & C OR B & C)

**To Reproduce**
1. Try provisioning  3 - 4 devices

**Expected behavior**
Should list all provisioned mesh nodes

**Platform details:**
 - Device: Galaxy A10s
 - OS: Android 9.0
 - App Version - 2.1.4

**Logs / Screenshots**
![Screenshot_20191206-123454_nRF Mesh](https://user-images.githubusercontent.com/13926468/70303218-139af380-1825-11ea-8e3d-bbc5e4a0015a.jpg)

In screenshot 0x0003 and 0x0005 are visible and 0x0004 is missing. (it was visible before provisioning 0x0005)

**Comment by roshanrajaratnam** [comment]
@hardiksingh-rathore do you know if the devices have unique device uuids? I suppose the device got overwritten because the device UUIDs were the same?

**Comment by hardiksingh-rathore** [comment]
Yes. the problem was because of the same UUIDs.
Thanks!
