### ISSUE TITLE
Import and export / IOS and android

### ISSUE THREAD

**Issue by Baothien1301** [NordicSemiconductor/Android-nRF-Mesh-Library#286]
Hi!
I found an issue:
- When i import a json file exported from IOS on android, it is success. But when i import a json file exported from Android on IOS, it is fail. And i read json files export from IOS and Android, i see difference. Json file export from Android have not "group" and when I add "group" and import again, it is success.
I think this issue will be solved soon.

**Comment by philips77** [comment]
Thank you for reporting the issue. The group field is mandatory, even if there are no groups.
FYI: the Json scheme is not finally defined yet same may change in the future. Hopefully no breaking changes, but until it's final you should not assume the Json files you generate more will work on future versions or other apps.
We will try to make the nRF Mesh apps accept current config files in the future.
