### ISSUE TITLE
Access PDU Op codes computed differently in iOS implementation

### ISSUE THREAD

**Issue by kiyoshi-brilliant** [NordicSemiconductor/Android-nRF-Mesh-Library#293]
---

**Describe the bug**
Logic to compute Op codes does not match iOS implementation. Also filing on iOS repo.
Most concerning is the default / else case treatment but the other cases are slightly mismatched as well.
Please provide guidance as to which is correct.

iOS issue here: https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/issues/260

Android:
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/fd90df15ebb03222ee6f7f7bb52587e1f7e60173/android-nrf-mesh-library/meshprovisioner/src/main/java/no/nordicsemi/android/meshprovisioner/utils/MeshParserUtils.java#L357-L366

iOS:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/68dc144aabdf99da472b809115d94358b843343d/nRFMeshProvision/Classes/Layers/Access%20Layer/AccessPdu.swift#L151

**To Reproduce**
1. View Op code computing code

**Expected behavior**
Should be logically equivalent.

**Platform details:**
N/A

**Logs / Screenshots**
N/A

**Comment by roshanrajaratnam** [comment]
Well you are correct they do look different but they both have the same function as intended. However I have made it a little bit similar.

**Comment by kiyoshi-brilliant** [comment]
Thanks! I think we had gotten confused about passing the op code w/ vs w/o the company identifier, we appreciate the changes!
