### ISSUE TITLE
check isProvisioningComplete

### ISSUE THREAD

**Issue by benjak135765** [NordicSemiconductor/Android-nRF-Mesh-Library#298]
Hi~
How can i get the "registerApp() - UUID" ?

I want check the device 
if not exist in nodes then isProvisioningComplete = false
at red area 

 
![image](https://user-images.githubusercontent.com/11077292/79668772-c58df780-81e9-11ea-9b89-317d28bcdd82.png)

**Comment by roshanrajaratnam** [comment]
@benjak135765 this is an Android system log. What are you trying to achieve?

**Comment by benjak135765** [comment]
my app want scan Provisioned Device.
only connect it, not Provisioning again
but i don'w know how can i get the node...

**Comment by roshanrajaratnam** [comment]
@benjak135765 I guess you mean that you want to  connect to the same device after restarting the app? You will have to scan for devices with devices advertising with the following 16-bit UUID 0x1828 and also match against the network id generated using the network key. Please refer to the sample app.
