### ISSUE TITLE
App Crashing when trying to bound newly created network key into newly created App Key.

### ISSUE THREAD

**Issue by ahmedmeeran** [NordicSemiconductor/Android-nRF-Mesh-Library#301]
---

**Describe the bug**
I wanted to use my own App key and Network key generated from the server. So I created a Network key first, which created under Sub Network Keys. Then I created the App key and tried to bound the newly created network key. The moment you select the newly created Network Key App is getting Crashed.

I want to use my own Net Key and App key is there any other way to achieve it?
Any helps would be appreciated.

**Reproduce Behaviour**
1. Go to "Settings Tab".
2. Click on "Network Keys".
3. Click on Button "ADD SUB NET KEY" on the bottom right corner.
4. Click on Button "SAVE" on the right top corner.
5. Go back to "Settings Tab".
6. Click on "App Keys".
7. Click on "ADD APP KEY" Button.
8. Click "Network Key 2"

**Platform details:**
 - Device: OnePlu 7 Pro
 - OS: Android 10.0
 - Library Version 2.1.4

**Image Attached**
![Screenshot_20200429-160202](https://user-images.githubusercontent.com/64530740/80588734-7ee49c80-8a36-11ea-88a1-29006e002e58.jpg)

**Comment by roshanrajaratnam** [comment]
@ahmedmeeran  Oops, thanks for catching this. Will fix it straightaway.
