### ISSUE TITLE
Mesh node provisioning

### ISSUE THREAD

**Issue by xiaofengming** [NordicSemiconductor/Android-nRF-Mesh-Library#304]
Do you use node distribution network? 

link open always times out

**Comment by roshanrajaratnam** [comment]
@xiaofengming what do you mean?

**Comment by xiaofengming** [comment]
PB-ADV Provisioning

step1: link open
step2: Provisioning Process
step3: link close

step1:link open   always times out ,,,,,
result ： EE59000101  
Instead of ： EE590000FF

**Comment by roshanrajaratnam** [comment]
That app does not do provisioning using advertising. As of now the library only support provisioning based on GATT.

**Comment by xiaofengming** [comment]
I know，Just ask

**Comment by roshanrajaratnam** [comment]
I will close the issue then :)

**Comment by xiaofengming** [comment]
ok
