### ISSUE TITLE
[REQUEST] Is it possible to specify TTL for single VendorModel message?

### ISSUE THREAD

**Issue by antoniovillanova** [NordicSemiconductor/Android-nRF-Mesh-Library#319]
Hi,

i was considering if it is possibile to specify a custom ttl for some vendol model specific messages. On iOS side i see that TTL parameter can be specified for whatever message we send using 

`unc send(_ message: MeshMessage,
              from localElement: Element? = nil, to model: Model,
              withTtl initialTtl: UInt8? = nil) throws -> MessageHandle`

Is there an Android equivalent?

Thank you.

**Comment by roshanrajaratnam** [comment]
@antoniovillanova please check #326.
