### ISSUE TITLE
ConfigCompositionDataGet not working

### ISSUE THREAD

**Issue by Eklow02** [NordicSemiconductor/Android-nRF-Mesh-Library#322]
Hi, maybe you can help me with this problem. I'am using your library for my own app. After I have provisioned a device I want to sent the `ConfigCompositionDataGet`. But this request is not working. Either nothing is happening or I get into `onTransactionFailed`. In your sample App it's working. I'm pretty sure I'm doing the same steps as in the sample app. Maybe you can help me out? I have attached my logs.

![Bildschirmfoto 2020-06-08 um 09 50 17](https://user-images.githubusercontent.com/15686826/84005978-45287f00-a96e-11ea-9594-91745159b82d.png)

**Comment by roshanrajaratnam** [comment]
@Eklow02 please bear with me, I have invalidly referenced and closed your issue. I will take a look at this in a while.

**Comment by Eklow02** [comment]
@roshanrajaratnam I will close this one. Don't need your help anymore. It was a problem with my ble connection ✌️
