### ISSUE TITLE
Scheduler Messages

### ISSUE THREAD

**Issue by Eklow02** [NordicSemiconductor/Android-nRF-Mesh-Library#335]
Do you already know when you want to implement scheduler related messages?

**Comment by philips77** [comment]
Hello,
I don't see those messages coming to the library this year. We plan to do new release in October-ish, but it's unlikely that those messages will be included. You may speed things up by submitting a PR! We will gladly accept it!

**Comment by Eklow02** [comment]
Sorry for the late reply.

unfortunately my client don't let me share the code with you 😢

**Comment by DevHachi** [comment]
Are there any news to this subject?

**Comment by roshanrajaratnam** [comment]
Hi, we don't have any updates on this right now as we are busy with some other tasks. We gladly accept pull requests if you get around implementing them :)

**Comment by roshanrajaratnam** [comment]
Hi @DevHachi thanks to @Eklow02 #448 fixes this.
