### ISSUE TITLE
Proxy data instable

### ISSUE THREAD

**Issue by kcjian** [NordicSemiconductor/Android-nRF-Mesh-Library#337]
---

My app receives proxy data by setting the proxy. The Publish Period of the device is 0.8 seconds per time. When the device scans for a specific beacon, the beacon  data will be sent to the app. 

Through the test, when there are ten devices in the mesh network and the number of peripherals is gradually increased to 40 beacons, the control of the device is basically ineffective (for example, turning on the light)， and the beacon data is sent to the app normally.

After a day of testing, the app will also make errors in receiving data, as shown in the figure below

**Platform details:**
 - OS: [ Android 8.0]
 - Library Version (v1.2.0)

**Logs / Screenshots**
![bug1](https://user-images.githubusercontent.com/15611112/89407076-ba3ae980-d750-11ea-8248-7f4bffe1e22e.png)
![bug2](https://user-images.githubusercontent.com/15611112/89407097-c0c96100-d750-11ea-8dbd-17aad8fa6b8c.png)
![bug3](https://user-images.githubusercontent.com/15611112/89407109-c45ce800-d750-11ea-8354-139e1cc74ffd.png)

I don't know why it happened,

What's more, why the number of beacons around the device has increased and the device can't be controlled,

Look forward to your reply.

**Comment by roshanrajaratnam** [comment]
@kcjian we don't plan to support version 1.2.0 anymore since the library has matured a lot since this version. I would suggest upgrading to the latest library 2.1.4 as it is the most stable version as of now.
