### ISSUE TITLE
Communication between two smartphones to create a chat

### ISSUE THREAD

**Issue by openmotion** [NordicSemiconductor/Android-nRF-Mesh-Library#339]
Hello 
can i use your library to communicate between two BLE smartphone or with google glass ?

---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform details:**
 - Device: [e.g. Pixel XL]
 - OS: [e.g. Android 8.0]
 - Library Version (or Commit)

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster

**Comment by philips77** [comment]
No, but you could try https://github.com/NordicSemiconductor/Android-BLE-Library if you really want to use Bluetooth LE. But there are many other ways to exchange information between Android phones. And Google Glass? Seriously?

**Comment by openmotion** [comment]
> No, but you could try https://github.com/NordicSemiconductor/Android-BLE-Library if you really want to use Bluetooth LE. But there are many other ways to exchange information between Android phones. And Google Glass? Seriously?

hello yes the last model of google glass
