### ISSUE TITLE
Add GenericDeltaSet for android

### ISSUE THREAD

**Issue by Kleak** [NordicSemiconductor/Android-nRF-Mesh-Library#344]
on iOS there is a `GenericDeltaSet` but not on android.
It would be great if the 2 platforms have the same capabilities.

**Comment by roshanrajaratnam** [comment]
Hi @Kleak, yes as of now this is not supported on Android due to other priorities. I will try to add it in the next release.

**Comment by R0m4in-dooz** [comment]
Hello @roshanrajaratnam ! We are using the library and need this feature for Android. Can we get a deadline on the future release containing GenericDeltaSet for Android ?

**Comment by roshanrajaratnam** [comment]
Hey @R0m4in-dooz unfortunately I cannot promise a deadline as I have some other priorities related to mesh and I will add this on one of the upcoming releases. However feel free to send us a pull request if you decide it to implement it yourself.

**Comment by R0m4in-dooz** [comment]
Allright thank you for quick response !
Well we have already some custom classes to wrap GenericMessage, but not sure if it could help you to indeed implement the feature. 
We will try to implement a workaround until a release containing this DeltaSet feature for Android is published 👍 Keep up the great work :)

**Comment by ZacharyTech** [comment]
It's been two years

**Comment by roshanrajaratnam** [comment]
Finally! #574 fixes this.
