### ISSUE TITLE
mesh packet reassembly termination implementation is wrong

### ISSUE THREAD

**Issue by haicongfu** [NordicSemiconductor/Android-nRF-Mesh-Library#354]
---

**Describe the bug**
The current implementation of reassembled mesh packet termination is based on last packet size which is wrong. It should be based on GATT_SAR_END bits in the incoming or outgoing packet. 

**To Reproduce**
User third party tool to generate two mesh segments, each segment equal to the MTU. 
Because the last segment length equals mtuSize, the function fails to produce the entire packet. 

In File  MeshManagerApi.java
private byte[] appendPdu(final int mtuSize, final byte[] pdu) {
 if (length < mtuSize) {
...
                final byte[] packet = mIncomingBuffer;
                mIncomingBuffer = null;
                return packet;
            }
...
}

suggested fix is 

private byte[] appendPdu(final int mtuSize, final byte[] pdu) {
 if (length < mtuSize) {
...
            final int pduType = MeshParserUtils.unsignedByteToInt(pdu[0]);
            if (pduType == ((GATT_SAR_END << SAR_BIT_OFFSET) | MeshManagerApi.PDU_TYPE_PROXY_CONFIGURATION)) {
                final byte[] packet = mIncomingBuffer;
                mIncomingBuffer = null;
                return packet;
            }
...
}

**Comment by roshanrajaratnam** [comment]
@haicongfu thanks for reporting this i'll take a look at this.

**Comment by roshanrajaratnam** [comment]
Sorry for the delayed reply, but is fixed and tested.
