### ISSUE TITLE
Deleting App Key Failed to remove from DB

### ISSUE THREAD

**Issue by harishkumar12k** [NordicSemiconductor/Android-nRF-Mesh-Library#359]
**Describe the bug**
Deleting the App Key for first time once it is created failed.
1. Add App Key(Application Key 2)
2. Delete App Key(Application Key 2)
3. Kill the App
4. Open App
5. Now in App List screen "Application Key 2" is still present, which was deleted previously.

**To Reproduce**
1. Go to App Key List screen.
2. Click on button "ADD APP KEY"(Even if i click on close OR save App Key is stored in DB).
3. Now, Deleted the key. Which is success now and even UI is updated, but close the App and open again the key is not deleted.
4. I have done same process using DBinspector with Live updates checked, App Key was not deleting for first time from App(Delete was successfully once App is closed and opened again)

**Expected behavior**
1. App Key should not be saved if we tap on cross icon in "Add App Key Screen".
2. App Key should be deleted even if we did not close the App.

**Platform details:**
 - Device: Pixel 4, API 28

**Screenshots**
In Mobile it shows 1 App Key, but in DB it still shows 3 App Keys
![Capture](https://user-images.githubusercontent.com/13382914/102046610-a770a980-3e01-11eb-81de-cec9e04e2a50.JPG)
![screenshot 1](https://user-images.githubusercontent.com/13382914/102047061-9d02df80-3e02-11eb-9376-6f6006f2f6f1.png)

**Comment by roshanrajaratnam** [comment]
@harishkumar12k nice catch, I'll fix this in the upcoming release!

**Comment by geestore117** [comment]
I believe this issue has been reintroduced in a newer release. It can be reproduced using the original comment above. 

Library version: no.nordicsemi.android:mesh:3.3.4
Google Play Store app version: 3.3.3
  
Platform details:

Device: Pixel 7A, API 34
