### ISSUE TITLE
Import network problems

### ISSUE THREAD

**Issue by xhtlxa** [NordicSemiconductor/Android-nRF-Mesh-Library#371]
---

**Describe the bug**
The node cannot be set normally after importing other networks.

**To Reproduce**
1. Settings-Export
2. Settings-Import
3. connect

**Expected behavior**
The node can be set normally.

**Platform details:**
 - Device: Android
 - OS: 8.0
 - Library Version (2.4.3)

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster

**Comment by xhtlxa** [comment]
> 设置节点是什么意思？您是否正在更改网络并期望能够访问旧网络中的节点？
I hope it can be used normally after importing the mesh. Later I found that it can be achieved by modifying the unicast address different from the previous one, but there are only a few thousand unicast addresses available and cannot be repeated with the previous ones. Is there any way I can clear the previous ones Unicast address cache

**Comment by roshanrajaratnam** [comment]
I believe the problem you are having is sending messages after exporting and importing a network on a different phone?
If so the reason for this not to work is the sequence number being exported or imported for security reasons. However you can have multiple provisioners in the network for different devices.. This way you don't have to modify the unicast address of the provisioners to send messages.

**Comment by xhtlxa** [comment]
> I believe the problem you are having is sending messages after exporting and importing a network on a different phone?
> If so the reason for this not to work is the sequence number being exported or imported for security reasons. However you can have multiple provisioners in the network for different devices.. This way you don't have to modify the unicast address of the provisioners to send messages.

I can’t use it after exporting and importing from the same mobile phone. Is there a way to directly clean up the unicast addresses that I have previously set?

**Comment by xhtlxa** [comment]
> I believe the problem you are having is sending messages after exporting and importing a network on a different phone?
> If so the reason for this not to work is the sequence number being exported or imported for security reasons. However you can have multiple provisioners in the network for different devices.. This way you don't have to modify the unicast address of the provisioners to send messages.

Or is there a way to clear the serial number cache?

**Comment by roshanrajaratnam** [comment]
If you had export >> reset >> imported again the sequence numbers are lost and the messages won't work sent from the same address because the nodes will have the last used sequence number. However, if you had just exported and imported it should just work out of the box, I will take at look at this on my end as well. 

If you want to change address of a provisioner you can do that in settings >> provisioner.

**Comment by xhtlxa** [comment]
> If you had export >> reset >> imported again the sequence numbers are lost and the messages won't work sent from the same address because the nodes will have the last used sequence number. However, if you had just exported and imported it should just work out of the box, I will take at look at this on my end as well.
> 
> If you want to change address of a provisioner you can do that in settings >> provisioner.

I can’t continue to use it after exporting and importing. It seems that the serial number has become zero, and the serial number of the node is still the previous one, so the message is filtered.

**Comment by xhtlxa** [comment]
> > If you had export >> reset >> imported again the sequence numbers are lost and the messages won't work sent from the same address because the nodes will have the last used sequence number. However, if you had just exported and imported it should just work out of the box, I will take at look at this on my end as well.
> > If you want to change address of a provisioner you can do that in settings >> provisioner.
> 
> I can’t continue to use it after exporting and importing. It seems that the serial number has become zero, and the serial number of the node is still the previous one, so the message is filtered.

Is there a way to get and modify the serial number?

**Comment by roshanrajaratnam** [comment]
Here's how to set the sequence number manually https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/05ccaf31796939e8e47d138e2a91bf37c24d54bf/mesh/src/main/java/no/nordicsemi/android/mesh/transport/ProvisionedMeshNode.java#L242-L253

**Comment by xhtlxa** [comment]
> Sets the sequence number 
>       * <p> 
>       *     This is only meant to be used internally within the library. 
>       *     However this is open now for users to set the sequence number manually in provisioner node

Excuse me, can this serial number overlap infinitely? Or will it automatically return to 0?

**Comment by xhtlxa** [comment]
> Here's how to set the sequence number manually
> 
> https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/05ccaf31796939e8e47d138e2a91bf37c24d54bf/mesh/src/main/java/no/nordicsemi/android/mesh/transport/ProvisionedMeshNode.java#L242-L253

Why is my getSequenceNumber always -1?

**Comment by roshanrajaratnam** [comment]
as I said, when exporting the network, we don't export the sequence number so when you import again it's reset.

**Comment by xhtlxa** [comment]
> as I said, when exporting the network, we don't export the sequence number so when you import again it's reset. It will reset to 0 after the IV Index procedure completes.

After the sequence is reset to 0, I cannot interact with the node. How to deal with this?

**Comment by roshanrajaratnam** [comment]
You will have to manually handle this in your app, this is the reason the library allows to set the sequence number manually. Sequence number is not exported due to security reasons.

**Comment by xhtlxa** [comment]
> You will have to manually handle this in your app, this is the reason the library allows to set the sequence number manually. Sequence number is not exported due to security reasons.

How do I receive the acquisition and modification sequence? The sequence I get with getSequenceNumber()  is always -1.

**Comment by roshanrajaratnam** [comment]
I will be changing the default sequence number to zero, however, like I said before sequence numbers are not exported so you will have to handle it manually. What I mean by handling manually is that keep track of the the sequence numbers. Because every time you export and import the network from a json file the sequence number is not present. Hence it can be -1 or will be 0 in the future. May be you can store  it in your app.

**Comment by xhtlxa** [comment]
> I will be changing the default sequence number to zero, however, like I said before sequence numbers are not exported so you will have to handle it manually. What I mean by handling manually is that keep track of the the sequence numbers. Because every time you export and import the network from a json file the sequence number is not present. Hence it can be -1 or will be 0 in the future. May be you can store it in your app.
> 
> What do you mean by acquisition and modification sequence?

What I think is getSequenceNumber()   before export and setSequenceNumber()   after import, but the value I get from getSequenceNumber()    before export is -1, is there a problem with my writing? 

sharedViewModel.getNodes().getValue().get(0).getSequenceNumber()

**Comment by roshanrajaratnam** [comment]
Sequence number is incremented for each message sent, so if your node has not sent any messages it can be -1.  But I see a slight issue in the library which can be misleading. https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/ac4a019cf8079a89f0830162ca614178efa92753/mesh/src/main/java/no/nordicsemi/android/mesh/BaseMeshNetwork.java#L1038-L1040

This should allow you to get the sequence number for a particular node.

**Comment by roshanrajaratnam** [comment]
@xhtlxa #395 this should help you start sending messages after exporting and importing the same network.
