### ISSUE TITLE
Provisioning Data Flag appears to be in wrong bit order

### ISSUE THREAD

**Issue by kiyoshi-brilliant** [NordicSemiconductor/Android-nRF-Mesh-Library#374]
---

**Describe the bug**
The provisioning flags do not appear to be the in the correct bit order.
[Android's implementation](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/81c6e9efec569d9dd9fa700ba9f96de7a2f05366/mesh/src/main/java/no/nordicsemi/android/mesh/MeshNetwork.java#L627) uses the two high-order/left-most bits, whereas [iOS implementation](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/f9a09aafe091e9597b99c6d615278a681d79561c/nRFMeshProvision/Classes/Provisioning/ProvisioningData.swift#L278) uses the two low-order/right-most bits.

**To Reproduce**
1. Set the MeshNetwork's IvIndex to an index with `isIvUpdateActive` set to True
2. Provision a device
3. Observe the Secure Network beacon emitted by the provisioned device
4. See that the beacon is advertising `normal operation` instead of the expected `IV Update Active`

**Expected behavior**
The Flag sent in the provisioning data should be formatted correctly (and the newly provisioned device should emit a Secure Network beacon with `IV Update Active`)
I believe the bit representation of the Flag should be identical on each platform (using the two low-order/right-most bits)

**Comment by roshanrajaratnam** [comment]
Nice catch and thanks for reporting this! Will fix this in the upcoming version.
