### ISSUE TITLE
Is provisioner check inside BaseMeshNetwork is wrong

### ISSUE THREAD

**Issue by Eklow02** [NordicSemiconductor/Android-nRF-Mesh-Library#399]
---

**Describe the bug**
The method ` public boolean isProvisioner(@NonNull final ProvisionedMeshNode node)` inside the `BaseMeshNetwork` return for all nodes inside the network true.  The method compares the meshUuuid but the id is always the same, because the uuid from the network is set after provisioning. 

**Expected behavior**
The check should compare the `provisioner.getProvisionerUuid()` with the `node.getUuid()`

**Platform details:**
 - Library Version `3.0.2`

**Comment by roshanrajaratnam** [comment]
Hi, I did not notice this issue until now and I already released a 3.0.3. I'll take a look at this now.

**Comment by roshanrajaratnam** [comment]
It's a stupid bug, I was comparing the network UUIDs instead of their own UUIDs, hence returning always true. Check out the latest Dev branch. You can close the issue, if it works for you.

**Comment by Eklow02** [comment]
Yes, I was also a little bit confused 😅. The fix is working for me👍
