### ISSUE TITLE
networkJson to MeshNetwork

### ISSUE THREAD

**Issue by xhtlxa** [NordicSemiconductor/Android-nRF-Mesh-Library#411]
Is there a way to convert networkJson to MeshNetwork?

**Comment by roshanrajaratnam** [comment]
Importing a mesh network  json will create a MeshNetwork object.

**Comment by xhtlxa** [comment]
Can I get the MeshNetwork object without importing the mesh?

**Comment by roshanrajaratnam** [comment]
As of now, no you cannot do that.

**Comment by xhtlxa** [comment]
I want to add or subtract lights in json and then switch back to json. Is there a better way?

**Comment by roshanrajaratnam** [comment]
hmmm right now thee is no possibility. I guess I should add functionality where users can add pre-provisioned nodes..

**Comment by xhtlxa** [comment]
If you just add a method to convert json to MeshNetwork, can you add it?

**Comment by roshanrajaratnam** [comment]
You can achieve the same thing by importing the mesh network json file.
