### ISSUE TITLE
Delay in sending data

### ISSUE THREAD

**Issue by Nuclear6** [NordicSemiconductor/Android-nRF-Mesh-Library#414]
hi, Why do I need to add a delay every time I send data? These delays are too long, can this time be changed?

**Comment by roshanrajaratnam** [comment]
Hi where do you add delays? is it something to do with longer messages with block acknowledgements?

**Comment by Nuclear6** [comment]
![image](https://user-images.githubusercontent.com/49468241/114334696-b5e78b80-9b7d-11eb-8b6f-9eb37c9bf338.png)
![image](https://user-images.githubusercontent.com/49468241/114334741-c861c500-9b7d-11eb-8a70-9f2dea703de9.png)
Delays have been added in these places.

**Comment by roshanrajaratnam** [comment]
Hi Nuclear you are free to remove these delays. I will remove them in the next release. These were added long time ago to ensure any messages weren't colliding this shouldn't be the case now.
