### ISSUE TITLE
Send a temporary message

### ISSUE THREAD

**Issue by xhtlxa** [NordicSemiconductor/Android-nRF-Mesh-Library#424]
How do I send a temporary message to the device I connected via mViewModel.connect(this, device, false)?

**Comment by roshanrajaratnam** [comment]
Hi could you elaborate your issue a little bit more please?

**Comment by xhtlxa** [comment]
How to send a message to a device after mViewModel.connect() instead of sending a message to the model under node

**Comment by philips77** [comment]
Hello,
Could you clarify what do you mean by temporary message? Or what View Model are you talking? What do you want to achieve? In Bluetooth Mesh you always send messages to all nodes, which may be consumed by some models on some nodes, so I don't know what is your question about.

**Comment by xhtlxa** [comment]
How can I send a message to the device without getting the Element and MeshModel of the node?

**Comment by roshanrajaratnam** [comment]
What is the message you are trying to send?

**Comment by xhtlxa** [comment]
Some byte[] defined by ourselves

**Comment by roshanrajaratnam** [comment]
Are you referring to a vendor model message?

**Comment by xhtlxa** [comment]
Yes, before you get Element and MeshModel

**Comment by xhtlxa** [comment]
solved
