### ISSUE TITLE
Inconsistent UUID formatting between iOS mesh export and Android mesh export

### ISSUE THREAD

**Issue by Cplantijn** [NordicSemiconductor/Android-nRF-Mesh-Library#425]
Sharing configurations between iOS and Android is problematic since node UUID formats differ between the two platforms. 

Example mesh export from `Android`: 
```
{
...
  nodes: [
    {
      UUID: "DDDEAD67-B371-61EF-0000-000000000000"
      name: "Christopher's Mesh Node",
      unicastAddress: "0001",
      ....
    }
  ]
....
}
```

Example mesh export from `iOS`:
```
{
...
  nodes: [
    {
      UUID: "DDDEAD67B37161EF0000000000000000"
      name: "Christopher's Mesh Node",
      unicastAddress: "0001",
      ....
    }
  ]
....
}
```
The UUID is a string in both cases, but the dashes are only present in the Android export. This inconsistency is also present in the `meshUUID` key in the JSON export.

**Describe the solution you'd like**
Consistent UUID string formatting for both android and iOS. Either the android drops the dashes, or the iOS version adds them in on mesh JSON export.

**Describe alternatives you've considered**
Right now I am just resolving the issue with some in-app string transformations to normalize them all to a format with the dashes. However I think this issue should be resolved in the library itself to make sure mesh JSON exports are cross platform compatible.

**Comment by philips77** [comment]
Are you using the latest ios version, which is 3.1.2?

**Comment by philips77** [comment]
This has change in nRF Mesh 3.0:
https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/commit/e095ffdc34c9dc710b5c0259a290fd735cb01e8b

If your cocoa pods doesn't find newer version, update cocoa pods in Mac.

**Comment by Cplantijn** [comment]
@philips77 Thank you for your suggestion. We went ahead and upgraded our iOS mesh library and we are getting expected casings for node UUIDs. Thank you.
