### ISSUE TITLE
ApplicationMessage public accessible

### ISSUE THREAD

**Issue by DevHachi** [NordicSemiconductor/Android-nRF-Mesh-Library#435]
**Is your feature request related to a problem? Please describe.**
Currently I can't implement my own messages, because I get an error when trying to inherit from ApplicationMessage.

`Cannot access '<init>': it is package-private in 'ApplicationMessage'
Cannot access 'ApplicationMessage': it is package-private in 'no.nordicsemi.android.mesh.transport'
'public' subclass exposes its 'public/*package*/' supertype ApplicationMessage`

It would be nice if I could implement my own messages, that nordic has not implemented because they are vendor specific or because they are not implemented yet.

It would be really awesome if this would be possible.

**Comment by roshanrajaratnam** [comment]
you may use VendorModelMessage to send vendor specific messages.
