### ISSUE TITLE
Where's the example mentioned in README? 

### ISSUE THREAD

**Issue by diida** [NordicSemiconductor/Android-nRF-Mesh-Library#438]
Hello
I'm sorry if I disturbed you.
I found description "Open 'Example/nRf Mesh Provisioner'" at install section in README file.
But I can't find the 'Example' folder.How can i get it?

**Comment by roshanrajaratnam** [comment]
Hi this is as an error on the Readme file. You should just clone the project and and open it on Android Studio. We changed the project and did not update the readme file.
