### ISSUE TITLE
return DaggerMeshApplication_HiltComponents_SingletonC.builder()   run error

### ISSUE THREAD

**Issue by 123yangu** [NordicSemiconductor/Android-nRF-Mesh-Library#445]
DaggerMeshApplication_HiltComponents_SingletonC  not find
![image](https://user-images.githubusercontent.com/6700363/130048915-13533b0f-10fb-4618-9291-0532a7895b82.png)

**Comment by 123yangu** [comment]
update  ext.hilt_version = '2.33-beta' 
delete //    implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha04"

run ok

**Comment by roshanrajaratnam** [comment]
Will close the issue since you have fixed this.
