### ISSUE TITLE
Could not get unknown property 'sonatypeStagingProfileId' for object of type io.github.gradlenexus.publishplugin.NexusRepository

### ISSUE THREAD

**Issue by LoongFei** [NordicSemiconductor/Android-nRF-Mesh-Library#449]
Build
Could not get unknown property 'sonatypeStagingProfileId' for object of type io.github.gradlenexus.publishplugin.NexusRepository

**Comment by roshanrajaratnam** [comment]
Hey, sorry about this, please comment out the following lines. I forgot to comment out the lines relating to mavenCentral publishing and this should fix your issue
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/build.gradle#L56
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/mesh/build.gradle#L78
