### ISSUE TITLE
Please provide a way to tell through which node the app is connected to.

### ISSUE THREAD

**Issue by NanaDada** [NordicSemiconductor/Android-nRF-Mesh-Library#452]
**Is your feature request related to a problem? Please describe.**
Our app provides a feature to disable a node's proxy model. This makes it quite easy for the user to lock herself/himself out of the mesh by disabling all proxy models.
To avoid this (for our target audience common situation), we need a way to tell through which mesh node the app is connected to the mesh.

**Describe the solution you'd like**
`ConnectionObserver.onDeviceConnected()` gets called with the connected `BluetoothDevice` as parameter. The `BluetoothDevice` instance contains the mac address.
If the `ProvisionedMeshNode` instances would also contain their mac address, we could easily tell with which node the app is connected to.

**Describe alternatives you've considered**
None, but any alternative approach would be welcome as well.

**Additional context**
Great libary btw. Thanks for providing it!

**Comment by roshanrajaratnam** [comment]
Hi thanks for your feedback. If your want this feature, this is more of a feature request to the [Android-BLE-Library
](https://github.com/NordicSemiconductor/Android-BLE-Library). The issue with using the mac address is that , it may change upon a power recycle or a firmware update depending on the firmware implementation.

Another approach to this would be, upon connecting to a proxy node you may send a whitelist filter message and upon receiving response you know the unicast address(src address) of the device which you can use to identify the proxy. 

If you are building a consumer app this feature should be hidden away in my opinion.
