### ISSUE TITLE
send unacknowledged message should not open DialogFragmentTransactionStatus

### ISSUE THREAD

**Issue by xiangxiangjiang** [NordicSemiconductor/Android-nRF-Mesh-Library#457]
unacknowledged message will not get the response from the remote node according to the ble mesh specification.
when I send unacknowledged message to the remote node, the app show the DialogFragmentTransactionStatus with R.string.operation_timed_out after a few seconds, it seems to wait for respons message.

**Comment by roshanrajaratnam** [comment]
@xiangxiangjiang could you confirm if the message is received on the node? Is it sent via a proxy node?

**Comment by xiangxiangjiang** [comment]
yes, I'm sure. I use the TI's simplelink launchpad cc2652r with sdk&nbsp;simplelink_cc13x2_26x2_sdk_5_20_00_52.&nbsp;My device was set as relay and proxy node, the node received the&nbsp;unacknowledged&nbsp;&nbsp;message&nbsp;that I send using vendor model controls in Vendor Model Actvity with Acknoledged Message checkbox unchecked and printed the message on the screen. Because the message from mobile is unack type, the node will not send the response message to the originor. And after I read the android app source code, I find that the sendmessage method start a runable to wait for response whatever the message type is ack or unack.&nbsp;

刘道明|daoming北京理工大学
手机：18811553599
***@***.***




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Roshan ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [NordicSemiconductor/Android-nRF-Mesh-Library] send unacknowledged message should not open DialogFragmentTransactionStatus (Issue #457)





 
@xiangxiangjiang could you confirm if the message is received on the node? Is it sent via a proxy node?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by roshanrajaratnam** [comment]
Hi is your vendor model message a segmented message? The runnable you are referring to is related to segmented messages.

**Comment by roshanrajaratnam** [comment]
Also you have a point here. Will fix this!
