### ISSUE TITLE
is here hava a open source Firmwares open source project?

### ISSUE THREAD

**Issue by mmlingyu** [NordicSemiconductor/Android-nRF-Mesh-Library#459]
---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform details:**
 - Device: [e.g. Pixel XL]
 - OS: [e.g. Android 8.0]
 - Library Version (or Commit)

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster

**Comment by roshanrajaratnam** [comment]
Hi you can download the nRF Connect SDK examples [here](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/samples_bl.html) or nRF Mesh SDK samples [here](https://www.nordicsemi.com/Products/Development-software/nRF5-SDK-for-Mesh/Download) or
