### ISSUE TITLE
Exclusion list filter with empty Address Array ignores messages

### ISSUE THREAD

**Issue by Eklow02** [NordicSemiconductor/Android-nRF-Mesh-Library#466]
**Describe the bug**
The DefaultNoOperationMessageState does not process the messages correctly, if the proxy filter  EXCLUSION_LIST_FILTER is set with an empty addresses range. 

**To Reproduce**
1. Set the Filtertype to EXCLUSION_LIST_FILTER, but don't add any addresses to the array yet. 
2. The method `isReceivedViaProxyFilter` returns true

**Expected behavior**
If there are no matching addresses the `isReceivedViaProxyFilter` method should return false.

**Platform details:**
 - Library Version 3.1.6
 
**Possible fix:**
```
private boolean isReceivedViaProxyFilter(@NonNull final Message message) {
        final ProxyFilter filter = mInternalTransportCallbacks.getProxyFilter();
        if (filter != null && !filter.getAddresses().isEmpty()) {
            if (filter.getFilterType().getType() == ProxyFilterType.INCLUSION_LIST_FILTER) {
                return filterAddressMatches(filter, message.getDst());
            } else {
                return !filterAddressMatches(filter, message.getDst());
            }
        }
        return false;
    }
```

**Comment by roshanrajaratnam** [comment]
Thanks for catching this.
