### ISSUE TITLE
Add group is broken if provisioner have more than 1 group range

### ISSUE THREAD

**Issue by Rawa** [NordicSemiconductor/Android-nRF-Mesh-Library#469]
---

**Describe the bug**
If a provisioner has more than 1 groups range the add Group function will always fail.

**To Reproduce**
In mesh app:
1. Go to provisioner
2. Add new group range, e.g E000-EFFF
3. Try and add a new group to any of the ranges, it will always fail

**Expected behavior**
Group should work in either range.

Problem relies here, if the group is outside any of the ranges create group will fail.

https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/mesh/src/main/java/no/nordicsemi/android/mesh/MeshNetwork.java#L434

**Comment by Rawa** [comment]
Same goes for the other function as well.
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/e03b1eba6cf4d7bb41b1fa36d3ce8055e8df4208/mesh/src/main/java/no/nordicsemi/android/mesh/MeshNetwork.java#L454

**Comment by Rawa** [comment]
Added a pull request for a fix:
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/pull/470

**Comment by philips77** [comment]
Good catch. Thank you for creating the issue and PR. We will look into it shortly.

**Comment by philips77** [comment]
I managed to replicate the issue using the most recent version.
