### ISSUE TITLE
Libraries in Flutter

### ISSUE THREAD

**Issue by SteMMo33** [NordicSemiconductor/Android-nRF-Mesh-Library#472]
Hi all,
I need to develop an application for the Nordic chips and I'd like develop it in Flutter.
I'm wondering if someone also try the develop similar projects and maybe confirm me that is possible to insert the *-nRF-Mesh libraries (both Android and ios) in the specific folders and use them as plugins.

Anyone?
Are there problems??

Thanks!

**Comment by R0m4in-dooz** [comment]
Hello @SteMMo33,
Yes it is possible to use the Nordic libraries in a Flutter project, we do it at our company 👍
We have a Flutter plugin that encapsulates Nordic native libraries and expose their API in Dart. The libraries are git submodules of the Flutter plugin. There are probably some other ways to do it such as importing library via the usual way (gradle scripts for Android), but we needed to fork the libraries and have custom cross-platform API. Our plugin is a private repository though, so I won't be able to share implementation..

Regards 🙂

**Comment by philips77** [comment]
Good to know that it's working!
Sorry that the Android and iOS APIs differ much. We will work on making it more similar.

**Comment by R0m4in-dooz** [comment]
Hello @SteMMo33,
We just open sourced our Flutter plugin that provides a Dart API to use this library and its iOS counterpart.
It still lacks some "get started" documentation, but the example app should be enough to jump in with basic mesh network features 👍 
If it can help you to develop your projects, feel free to give [our plugin](https://pub.dev/packages/nordic_nrf_mesh) a try !
Regards 👋
