### ISSUE TITLE
Build error when running dev branch tests 

### ISSUE THREAD

**Issue by gujor** [NordicSemiconductor/Android-nRF-Mesh-Library#473]
**Describe the bug**
Build error when running dev branch tests.

**To Reproduce**
1. Switch to dev branch.
2. Run tests.

**Expected behavior**
Tests should build and run.

**Platform details:**
 - Android Studio
 - dev branch

**Logs / Screenshots**
<img width="615" alt="Screen Shot 2022-02-09 at 08 05 13" src="https://user-images.githubusercontent.com/36726279/153139612-93543436-19c8-43fb-8541-87781ae53747.png">

**Comment by roshanrajaratnam** [comment]
Hi thanks for reporting this. Will fix this.

**Comment by gujor** [comment]
Thanks. I have created a PR with the fixed we used. If it looks ok, feel free to use it, and maybe save some time :)

**Comment by roshanrajaratnam** [comment]
There were some tests that was added in a pull request we got with the scheduler feature that may have had this issue. Thanks for your PR.
