### ISSUE TITLE
ProvisionedMeshNode unicast address is always 1

### ISSUE THREAD

**Issue by choi-seung-min** [NordicSemiconductor/Android-nRF-Mesh-Library#482]
Hi, I was debugging for issue #480 
then, I found my app always get ```ProvisionedMeshNode.getUnicastAddress()``` as 1
before I createMeshPdu with ```nrfMesh.mMeshManagerApi.createMeshPdu(node.getUnicastAddress(), new ConfigNodeReset());```.

I've reset the mesh device, and network. but it's always return 1 for ```getUnicastAddress()``` for any node.

before I createMeshPdu, I do
1. ```nrfMesh.connect(getContext(), device, isReconnect);```
2. ```nrfMesh.identifyNode(device);```
3. ```nrfMesh.mMeshManagerApi.startProvisioning(node);```

after provisioning is finished, I seletct my node with ```nrfMesh.setSelectedMeshNode(node);```.
 go to configuration page and call 
```
final ProvisionedMeshNode node = nrfMesh.getSelectedMeshNode().getValue();
if (node != null) {
    nrfMesh.mMeshManagerApi.createMeshPdu(node.getUnicastAddress(), new ConfigNodeReset());
    nrfMesh.isConnectedToProxy().removeObservers(this);
    result.success(true);
}
```

I do connection check before I call method above.

I followed Android Nrf-Mesh app's flow to implement this features in flutter.
As I did it, without any document, I'm not sure I did correctly with provisioning and resetting process.

Why do I get always 1 as result of ```getUnicastAddress()```?

**Comment by roshanrajaratnam** [comment]
Calling `getUnicastAddress()` will give you the unicast address of that node.

P.S: Also a Provisioner with an address in your mesh network is also a node in a mesh network.
