### ISSUE TITLE
CID needs to be updated

### ISSUE THREAD

**Issue by zerosensei** [NordicSemiconductor/Android-nRF-Mesh-Library#484]
---
Now the CID has been increased to [0x0B38](https://www.bluetooth.com/specifications/assigned-numbers/company-Identifiers/).

**Comment by roshanrajaratnam** [comment]
@zerosensei Will update the company identifiers for the next version. We gladly accept pull requests too.

**Comment by philips77** [comment]
Related for iOS: https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/issues/404
