### ISSUE TITLE
OpCode 0x8046 not correctly implemented

### ISSUE THREAD

**Issue by SalimTerryLi** [NordicSemiconductor/Android-nRF-Mesh-Library#499]
---

**Describe the bug**

According to page 174 of 333, [Mesh Profile 1.0.1](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=457092), the opcode 0x8046 contains a two octets param which indicates netkey index.

But the implement [here](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/543d7630a5ecb6250dcb5c17c455bcd9da0baa64/mesh/src/main/java/no/nordicsemi/android/mesh/transport/ConfigNodeIdentityGet.java#L28) does not follow the definition

**Comment by roshanrajaratnam** [comment]
Hi @SalimTerryLi, thanks for catching this. I will push a fix shortly.
