### ISSUE TITLE
nRF Mesh could not scaned my node device

### ISSUE THREAD

**Issue by chinli** [NordicSemiconductor/Android-nRF-Mesh-Library#514]
---

**Describe the bug**
I used Mynewt-nimble  to create node with pb_adv, but nRF Mesh could not scaned my device(in Scanner page not display).

**To Reproduce**
1. power on my ble device, and enable unprovisioned beacon adv;
2. use nRF Connect could scaned this device;
3.  use nRF Mesh, click the <ADD NODE> to enter the scanner page, but didn't displey always;

**Expected behavior**
nRF Mesh can scaned my device, and start to provisioning.

**Platform details:**
 - Device: HuaWei HONOR P6
 - OS: [e.g. Android 11.0]
 - Version of nRF Mesh: 3.2.4

**Logs / Screenshots**
adv data with hci log:
![图片](https://user-images.githubusercontent.com/7111302/171598361-fc95a21c-2c27-47b9-a6fb-5142ea2f0952.png)

scan result with nRF Conenct
![图片](https://user-images.githubusercontent.com/7111302/171598725-eb9a1210-eeb9-4975-8deb-d0efa5f48e6c.png)

thanks~

**Comment by roshanrajaratnam** [comment]
@chinli this is strange. Did you scan via "Add Node"?

**Comment by chinli** [comment]
@roshanrajaratnam Yes, I'm a little confused that it must be enable pb_gatt or not?  I wonder if you could suggest some testing.
thanks ~

**Comment by roshanrajaratnam** [comment]
Hi, I'm not sure if I could answer you on my-newt nimble. If the device is advertising you should be able to see the device in the scanner.

**Comment by roshanrajaratnam** [comment]
@chinli are you still facing this issue?

**Comment by chinli** [comment]
Unfortunately, this issue remains. but i enable both of pb_adv and pb_gatt, then nRF Mesh APP can display my device, provionsoning successful.
In my opinion, is APP not support pb_adv only or not?

**Comment by chinli** [comment]
Got it~~
