### ISSUE TITLE
Incorrect Retransmit Interval Step

### ISSUE THREAD

**Issue by RobertoGab** [NordicSemiconductor/Android-nRF-Mesh-Library#519]
Hello,
We are actually using an old version of Mesh library : 2.1.4
We cannot currently upgrade at the moment per customer guidance.

That said , we are having a problem configuring a device.

Context :
We send a Publish Message using a custom vendor message (using your lib's ConfigModelPublicationSet.java object).
As Retransmit Count we set 2 and as Retransmit Interval Step we set 5

Message sent  : 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/102740474/172174477-70215039-8bcc-495c-99ed-1f8d28d29623.png">

What goes wrong : 
If we get the dump of the communication to the Device the retransmit count differs from the one we set before (5), iOS seems to behave correctly, while on Android  the dump is as follow , with a retransmit count of 20.
***********
SIG model
Model ID : 0x1205
Element :1
Appkey BOUND
Retransmit count :2
Retransmit step :20
TTL :255
PUB ADDR : 0xC000
***********

Why is that ? Can we fix it somehow ?

Thanks in advance.

**Comment by RobertoGab** [comment]
Thank you so much Roshan ! 
Yes I will push some more to make it clear to client it is important to upgrade, meanwhile I'll try to fix it manually using the link you provided.
Thanks again :)

**Comment by roshanrajaratnam** [comment]
Good luck with it :)
