### ISSUE TITLE
Samsung Galaxy Tab A8 does not work with nRF Mesh Android App

### ISSUE THREAD

**Issue by ashored-aross** [NordicSemiconductor/Android-nRF-Mesh-Library#520]
---

**Describe the bug**
basically everything works great on our Galaxy Tab S6 Lite (SM-P610), can provision, everything. Same for the iOS version. However on the Samsung Galaxy Tab A8 (SM-X200) can see the device to be provisioned, but fails to provision it after the first steps.

We're using the 833 dev kit with soft device 140.  

Thanks

**To Reproduce**
1. Go to provisioning page, attempt to provision device
2. Device fails to provision after step shown below (fails silently) 

**Expected behavior**
Device provisioning fails 

**Platform details:**
 - Device: Samsung Galaxy Tab A8 (SM-X200)
 - OS: Android 11
 - Library Version (or Commit): 3.2.4

**Logs / Screenshots**
Add any logs or screenshots that can help us debug the issue faster
![Screenshot_20220608-094843_nRF Mesh jpg-960x720](https://user-images.githubusercontent.com/65681320/173094205-8cc97a1c-df21-472b-b227-61202d1716bf.jpg)

**Comment by roshanrajaratnam** [comment]
Hi as far as I am aware, there is a ticket open on DevZone already on this and tech support is looking in to this issue. Let's not duplicate issues. Hence closing this!
