### ISSUE TITLE
Provide option to process Nrf library logs

### ISSUE THREAD

**Issue by anees17861** [NordicSemiconductor/Android-nRF-Mesh-Library#521]
**Is your feature request related to a problem? Please describe.**
The Library relies on Android Native Logging. This way we can observe logs by connecting to laptop but can't observe for remote devices

**Describe the solution you'd like**
I can think of following two options where option 1 seems the easier approach)
1. Provide an option to set callback for logger interface
2. Allow to extend MeshManagerApi which has a default implementation of a log function. (Same as BleManager from the nordic ble library)

**Describe alternatives you've considered**
Couldn't find any other way

**Additional context**
The reason why we require this is to debug an issue where fetch composition data doesn't receive response if there are 20+ devices nearby that are provisioned in the same network.

**Comment by anees17861** [comment]
Will it be alright if I submit a PR to the same so that you can integrate it as quickly as possible?

**Comment by roshanrajaratnam** [comment]
Hey, we gladly accept pull requests :)

**Comment by anees17861** [comment]
Hi @roshanrajaratnam 
Sorry for the delay but I have created a pull request #522 

Please go through the same and see if it has any issues

**Comment by roshanrajaratnam** [comment]
Thanks I will take a look at this later today!
