### ISSUE TITLE
Revisit to closed Issue #518

### ISSUE THREAD

**Issue by Brew317** [NordicSemiconductor/Android-nRF-Mesh-Library#525]
---

Issue 518 has all the information.
and I will bring this up directly with Nordic as was suggested when 518 was closed
but I have new information that might allow you to duplicate the problem
When I reported the problem of nr Mesh only remembering that last node it provisioned I was using nr5340DK eval boards, or a mix of nr5340DK and nr52840DK eval boards.

Now I am only using nr52840DK boards and the problem has gone away
if I bring back a nr5340DK into the mix the problem reoccurs .

exact same code for all just different builds of course.

**Comment by roshanrajaratnam** [comment]
Hi thanks for reporting this issue. Seems like it's related to the firmwares or the build)build configurations itself. I would recommend creating a ticket on devzone as this is not directly related to he mesh library. The tech support should be able to help on this.
