### ISSUE TITLE
Multiple node provisioning at the same time.

### ISSUE THREAD

**Issue by tushar-patil-android** [NordicSemiconductor/Android-nRF-Mesh-Library#526]
**As per our current implementation we can add only one node at a time**
Currently user can provision only one device at a time, this solution seems good if we have limited devices to provision. But it got hectic if we have many devices to provision.

**Do we have have upcoming feature release for this?**
It will be good if we can provision multiple devices on the same time in same network.

**Comment by roshanrajaratnam** [comment]
Hi, yes as of now the library supports adding one node at a time. One of the reasons is that when provisioning you might have to enter use input/output authentication methods to authenticate. When provisioning multiple nodes this would make it even more complicated process for the user. Therefore we don't see us adding this feature.
