### ISSUE TITLE
A problem occurred evaluating project ':nordic_nrf_mesh'.

### ISSUE THREAD

**Issue by Hung6129** [NordicSemiconductor/Android-nRF-Mesh-Library#536]
I have a problem that when I run the application on flutter, it gives me this error in the terminal

FAILURE: Build failed with an exception.
* Where:
Build file 'C:\%user%\flutter\.pub-cache\hosted\pub.dartlang.org\nordic_nrf_mesh-0.12.0\android\build.gradle' line: 44
* What went wrong:
A problem occurred evaluating project ':nordic_nrf_mesh'.
> Project with path ':mesh' could not be found in project ':nordic_nrf_mesh'.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

that line 44 is come from the nordic_nrf_mesh library

i don't know how to fix it

all i want to do is use the  nordicNrfMesh.scanForUnprovisionedNodes 

Pls help me

**Comment by roshanrajaratnam** [comment]
@Hung6129 this seems to be a question best suited for stackoverflow as we cannot help support with flutter as of now.
