### ISSUE TITLE
How to control bluetooth mesh on other phones?

### ISSUE THREAD

**Issue by DM-Li-Lee** [NordicSemiconductor/Android-nRF-Mesh-Library#542]
I created network 1 on phone A and I want to control network 1 on phone B. Is there a way to share the data of mobile phone A to mobile phone B, so that mobile phone B can control network 1.

**Comment by philips77** [comment]
I transferred the issue here, as it's related to mesh, not BLE library.

If you want to control send data between 2 phones you need 2 other proxy nodes: one relaying packets to each phone: 
```mermaid
flowchart LR;
    A <-- GATT-->P1;
    P1 <-- ADV -->P2;
    P2 <-- GATT-->B;
```

**Comment by philips77** [comment]
Mind, that the current version of the Android library does not support Server models automatically, not even Config Server. You can implement it on your own by handling selected message types and replying with Statuses. 

The iOS mesh library supports Config Server and Scene server models, and allows to define your own models, both server and client. We're working on bringing this functionality to Android as well, but this will come in 2023 (hopefully).

**Comment by roshanrajaratnam** [comment]
Also if you just want to share the data between two phones you can export the mesh network and import it on phone B. Just create a new provisioner and you should be able to control without needing the config server support.
