### ISSUE TITLE
Import a mesh that contains a node with TransmissionSettings count 8 will fail

### ISSUE THREAD

**Issue by Rawa** [NordicSemiconductor/Android-nRF-Mesh-Library#550]
---

**Describe the bug**
Import a mesh that contains a node with TransmissionSettings count 8 will fail

See PR:
https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/pull/549

The function throws and error if value is 0-7 but, the actual value that is to be checked is 1-8.

**Comment by philips77** [comment]
Merged!
