### ISSUE TITLE
Netkey command not following mesh specifications

### ISSUE THREAD

**Issue by Shane555** [NordicSemiconductor/Android-nRF-Mesh-Library#553]
---

**Describe the bug**
When i use the nRF mesh app to delete a netkey from my ble mesh mcu, the command config netkey delete received contains a net index of 0xffff instead of the net index that i wish to delete. The mesh specifications says 
![image](https://user-images.githubusercontent.com/29925759/212588877-e756b374-4b64-42f1-9db0-faccf61e39fa.png)

**Expected behavior**
When i delete netkeys using the android app, for example, if i wish to delete net index 0x0002 from the device of interest, i will expect the delete netkeys command to send a message containing net index 0x0002.

**Platform details:**
 -  nRF mesh app Device: [Pixel 4A]
 - OS: [Android 13]
 - Version 3.2.4
- device of interest: ble mesh module

**Comment by roshanrajaratnam** [comment]
Hi Shane, thanks for reporting this issue. I will take a look at this and get back to you!

**Comment by Shane555** [comment]
@roshanrajaratnam hi, any news on this?

**Comment by roshanrajaratnam** [comment]
@Shane555 this seems to be working fine on our end. I am able to add and remove the said key index. Note that the key indexes are 12-bits long and is packed to two octets. Check table 4.3.1.1.
