### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by JulesDommartin** [NordicSemiconductor/Android-nRF-Mesh-Library#555]
There are some features that i would like to use in my personal project that has been implemented and merged in the repo as the GenericBatteryGet command for example.

When those features will be available as a release so I can get them from jcenter or maven ?

Thank you.

**Comment by roshanrajaratnam** [comment]
Hi, yes we will look in to this.

**Comment by JulesDommartin** [comment]
Hello, any update on this ?

**Comment by roshanrajaratnam** [comment]
A release is imminent!

**Comment by roshanrajaratnam** [comment]
Version 3.3.0 is now available!
