### ISSUE TITLE
Szene Register Status is ignored for Scene Register Get Message

### ISSUE THREAD

**Issue by Eklow02** [NordicSemiconductor/Android-nRF-Mesh-Library#557]
---

**Describe the bug**
The Scene Register Status is only parsed for the Scene Store, Scene Recall and Scene Delete Message. The Scene Register Get Message is missing inside the `parseAccessMessage` of the `DefaultNoOperationMessageState`

**Comment by roshanrajaratnam** [comment]
Hi thanks for reporting this, will take a look at this.

**Comment by roshanrajaratnam** [comment]
@Eklow02 do you mind giving this a spin please? I don't have a setup right now!
