### ISSUE TITLE
Composition DataGet - page number

### ISSUE THREAD

**Issue by mpiffari** [NordicSemiconductor/Android-nRF-Mesh-Library#563]
Hello folks and hi @roshanrajaratnam,
I'm here to ask you a question about CompositionDataGet operation: it is not clear why, in Android-Nrf-Mesh-Library the COMPOSITION_DATA_PAGE constant is set to 0xFF default value, despite in SIG specification (MeshProfile v1.0.1) is noted that only one page is available for composition data (see following screenshots).

![Screenshot 2023-07-25 at 11 39 39](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/assets/28917444/323ca591-0e0c-4aa3-86b5-6b1de175f773)

![Screenshot 2023-07-25 at 11 43 41](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/assets/28917444/d35105f3-39c8-4346-8b67-fcd99c392bf7)

**Comment by roshanrajaratnam** [comment]
Hi, it is mandatory to have composition data page 0 for all mesh nodes. However there can be additional pages. As the spec states the additional pages are optional. By sending 0xFF you will receive all the composition data pages available on the mesh node.

The upcoming mesh specification 1.1 will add more clarity to this.

Hope this clarifies.
