### ISSUE TITLE
nRF-Mesh-Library for kotlin multiplatform mobile (KMM)

### ISSUE THREAD

**Issue by vkurkchi** [NordicSemiconductor/Android-nRF-Mesh-Library#565]
As Kotlin Multiplatform gains more traction, I've been wondering if you folks might be working on KMM support for the upcoming releases. It'd be great to have a shared codebase, especially since there are already multiplatform libraries for dealing with BLE, like Kable.

**Comment by roshanrajaratnam** [comment]
Hey yes rightly so, we are currently working on a Kotlin library that will eventually deprecate the existing java library. Hopefully it should be ready by the end of the year. Once we have the Kotlin library in place, we will look into adding support to KMM as well.
