### ISSUE TITLE
BleMesh 1.1 Directed Forwarding Feature

### ISSUE THREAD

**Issue by Nuclear6** [NordicSemiconductor/Android-nRF-Mesh-Library#569]
Are there any plans to add the new features of Bluetooth mesh 1.1 to the current library?

**Comment by roshanrajaratnam** [comment]
Hi, unfortunately we won't be adding Bluetooth Mesh 1.1 features to this library. 

However we are currently working on a Kotlin version of the library that will be releasing an early version with some of the 1.1 features.

**Comment by Nuclear6** [comment]
Thanks
