### ISSUE TITLE
Wrong segmentation of Messages where the Payload length is >12 Octets but smaller than 15 octets

### ISSUE THREAD

**Issue by bengy** [NordicSemiconductor/Android-nRF-Mesh-Library#579]
---

**Describe the bug**
We noticed Light HSL Set Unacknowledged messages were sent segmented when sent from Android phones while they should be unsegmented.

The message length is 13 Bytes and the Mesh specification states:
> # 3.5.3 Segmentation and reassembly
> To transmit Upper Transport PDUs larger than 15 octets, the lower transport layer segments and
> reassembles Upper Transport PDUs...

Looking into the code it seems the [check in the LowerTransportLayer](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/776dadf0afb0eafc11a622c7b5d859e95524b4e9/mesh/src/main/java/no/nordicsemi/android/mesh/transport/LowerTransportLayer.java#L121) is wrong:
```
@Override
    @VisibleForTesting(otherwise = VisibleForTesting.PROTECTED)
    public final void createLowerTransportAccessPDU(@NonNull final AccessMessage message) {
        final byte[] upperTransportPDU = message.getUpperTransportPdu();
        final SparseArray<byte[]> lowerTransportAccessPduMap;
        if (upperTransportPDU.length <= MAX_SEGMENTED_ACCESS_PAYLOAD_LENGTH) {
            message.setSegmented(false);
            final byte[] lowerTransportPDU = createUnsegmentedAccessMessage(message);
            lowerTransportAccessPduMap = new SparseArray<>();
            lowerTransportAccessPduMap.put(0, lowerTransportPDU);
        } else {
            message.setSegmented(true);
            lowerTransportAccessPduMap = createSegmentedAccessMessage(message);
        }

        message.setLowerTransportAccessPdu(lowerTransportAccessPduMap);
    }
```
this should check for `<= MAX_UNSEGMENTED_ACCESS_PAYLOAD_LENGTH` which is 15 as expected.

iOS seems to have the [correct checks](https://github.com/NordicSemiconductor/IOS-nRF-Mesh-Library/blob/267216832aaa19ba6ffa1b49720a34fd3c2f8072/Library/Layers/Upper%20Transport%20Layer/UpperTransportLayer.swift#L115)

**Comment by roshanrajaratnam** [comment]
Hi, nice catch. Expect a release soon
