### ISSUE TITLE
Select mesh node based on src address

### ISSUE THREAD

**Issue by roshanrajaratnam** [NordicSemiconductor/Android-nRF-Mesh-Library#61]
Currently the app disregards the src of the messages and assumes that its the same node as the user is already communicating with. This may lead to wrong node being updated when receiving messages.

**Comment by DomiR** [comment]
This is very important to us, do you have an ETA? We need to get updates from a node, based on the publish group it is sending messages to, as we want to be able to control the light via external button and still get the update in our app. BUTTON (should publish to 0xC001)=>(will subscribe to 0xC001) GENRIC ON OFF (should publish to 0xC002) => App (get on off changes)

**Comment by roshanrajaratnam** [comment]
@DomiR As a matter of fact this is already in place in the library. I might have missed out on referencing this issue. If configured to suit your needs, app will get on/off commands in addition to the status (if you are sending acknowledged on/off). IMHO you should have the light bulb publish the status back to the app instead of having the app listen to the on/off message as well as the status on the subscribe group.

Still to get continuous updates you will have to implement the Proxy Whitelist message to receive continuous status updates. You have to send a message to the proxy to get one back unless your app's unicast is on the whitelist of the proxy. Implementing the proxy whitelist message would fix this for you. This is something I plan on adding, i'm currently working on importing and exporting networks so i would say, probably by end of next week I should have the whitelisting in place.
