### ISSUE TITLE
Add support for sending real time Generic Level values

### ISSUE THREAD

**Issue by roshanrajaratnam** [NordicSemiconductor/Android-nRF-Mesh-Library#72]
As a user/developer this would allow setting real time values to a generic level mode.

**Comment by DevelopertwoAtBubblyNet** [comment]
May I ask why this was originally added, then removed, and then eventually closed? This is a feature I have been attempting to get working but have been struggling with. Any hints on how to go about adding it? I understand its probably not a top priority for you.

**Comment by roshanrajaratnam** [comment]
Hi @DevelopertwoAtBubblyNet, this is more like a feature towards the app not the library itself so its not a top priority for us, but it still remains in our internal backlog. One way to implement this is to divide the seekbar in to 10 or 20 points and when reaching each point you can send an unacknowledged generic level message, this way you will not overwhelm with so many messages.
