### ISSUE TITLE
control each lights individually through application

### ISSUE THREAD

**Issue by pavan-hr** [NordicSemiconductor/Android-nRF-Mesh-Library#74]
I'm using nRF52 DK, mesh SDK version 2.2.0

I want give demo of the Light-Switch example application by forming network through mobile. I found that through mobile application switch, we cannot control the lights. Is there any mobile application apart from nRF Mesh (android/IOS). And yeah through switch device I can on/off the lights but not through mobile application.  

My requirement is:

1. Control the lights subscribed to particular switch through that switch in mobile app.

2. Control all lights individually.

**Comment by roshanrajaratnam** [comment]
Hi @pavan-hr you need to go in to the GenericOnOffServerModel in the particular model and turn on the lights and this should work for you. Make sure you bind an app key to the model before you try to turn on/off. 

PS. Please report these issues on [devzone](https://devzone.nordicsemi.com/) and you're guranteed to get a faster answer there.

**Comment by pavan-hr** [comment]
Hi Roshan,
I have already reported there. but they referred to github. 
https://devzone.nordicsemi.com/f/nordic-q-a/39262/nordic-mesh2-2-0-implementing-through-mobile-application

I have bind the application key to the model. But my concern is if a switch is publishing at lets say C001 publishing address, if 3 lights subscribe to the same C001.  Now, if you go to light 1 and try to on/off other 2 lights also turn on/off since they are subscribed to C001. Is there any way to control each light ?

**Comment by roshanrajaratnam** [comment]
@pavan-hr I see the problem you have faced. One thing we could do is not to publish the message to the whole group at all and just send it only to that particular bulb.  As of now we don't think we will be implementing this feature any soon as there are some more important issues in our backlog, but its something we can add to our backlog.
