### ISSUE TITLE
Handle multiple generic onoff server models with different elements on same device

### ISSUE THREAD

**Issue by DomiR** [NordicSemiconductor/Android-nRF-Mesh-Library#75]
**Is your feature request related to a problem? Please describe.**
We have devices with multiple elements, that all support genericOnOffServer. Sending acknowledged messages return status messages, but it is not clear, which element sent which message. Currently the callbacks for onGenericOnOffStatusReceived won't allow to determine from which element these messages came from.

`public void onGenericOnOffStatusReceived(ProvisionedMeshNode node, boolean presentOnOff, Boolean targetOnOff, int transitionSteps, int transitionResolution)`

**Describe the solution you'd like**
We would like to have `public void onGenericOnOffStatusReceived(ProvisionedMeshNode node, Integer elementAddress, boolean presentOnOff, Boolean targetOnOff, int transitionSteps, int transitionResolution)` where **Integer elementAddress** (or if preferred byte[] elementAddress) is added to all callbacks, that are coming from a specific element, but does not have the element address in the actual payload.

I'd be happy to submit a pull request. Is there any eta on #73 so I can wait for it?

**Comment by roshanrajaratnam** [comment]
@DomiR Yes this was something missing in the library and is being worked on as we speak. This issue will be fixed once I'm done implementing #73. The plan is that I should have it ready by next week.

**Comment by DomiR** [comment]
Hey @roshanrajaratnam, thank you for your reply. I saw that you are restructuring callbacks. Adding access to the message or the src of the message would be nice. If I can help, let me know 👍

**Comment by roshanrajaratnam** [comment]
@DomiR Sorry for the delay on thsi and I have been away from work for a few days. 

I have made a quite a lot of changes to the internals of the library. I also tried to keep the breaking changes to a minimum on the API. Some feedback would be really appreciated, on [this](https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/tree/improvements/fix-repository) branch. As an example getting composition data from a node will look like the following sendConfigMessMessage(ConfigCompositionDataGet)`

**Comment by DomiR** [comment]
Wow, this was a lot of work, thank you very much for this huge effort. I've been checking out the new structure and the new api feels much cleaner as one only needs to implement one callback and handle just the necessary cases. I have a bit of rewriting to do to test this in our app, but from what I can tell these are much welcomed improvements.

**Comment by roshanrajaratnam** [comment]
@DomiR Thanks for the feedback. Some of these changes were much needed and had to be addressed at some point. Sooner the better I suppose. Anyways hope there's not too many breaking changes.
