### ISSUE TITLE
control each lights individually through application

### ISSUE THREAD

**Issue by pavan-hr** [NordicSemiconductor/Android-nRF-Mesh-Library#76]
I'm using nRF52 DK, mesh SDK version 2.2.0

I want give demo of the Light-Switch example application by forming network through mobile. I found that through mobile application switch, we cannot control the lights. Is there any mobile application apart from nRF Mesh (android/IOS). And yeah through switch device I can on/off the lights but not through mobile application.
I have bind the application key to the model. But my concern is if a switch is publishing at lets say C001 publishing address, if 3 lights subscribe to the same C001. Now, if you go to light 1 and try to on/off other 2 lights also turn on/off since they are subscribed to C001. Is there any way to control each light ?

My requirement is:

1.Control the lights subscribed to particular switch through that switch in mobile app.
2.Control all lights individually.

**Comment by roshanrajaratnam** [comment]
Hi @pavan-hr, please do not create duplicate issues just to get an answer. This will only create confusion among other users and us.. Thanks for understanding!
