### ISSUE TITLE
Library usage example + clean methods.

### ISSUE THREAD

**Issue by misl6** [NordicSemiconductor/Android-nRF-Mesh-Library#95]
**Is your feature request related to a problem? Please describe.**
As a dev, It's still a nightmare trying to get the library working in my custom app. (non-native)

**Describe the solution you'd like**
- Usage README. The provided snippet is useless.

**Describe alternatives you've considered**

**Additional context**

**Comment by roshanrajaratnam** [comment]
@misl6 Sorry about this, the library is still not ready for production and we are continuously trying to improve this library. You can find the example app as reference.
