### ISSUE TITLE
the method  "mViewModel.getMeshNode()" returns wrong params

### ISSUE THREAD

**Issue by ZhanQiDong** [NordicSemiconductor/Android-nRF-Mesh-Library#98]
when the device  is connected，i try to press the IDENTFY Button , but the method mViewModel.getMeshNode()  returned wrong params.   params in method meshNode.getMeshNode() are all null;

**Comment by roshanrajaratnam** [comment]
Hi  when you call identifiy, you get a callback with the onProvisioningStateChanged(). You get an unprovisioned node object with the capabilities.
